// Generated by  grogu  starting from JINJA templated  MODULE_TEMPLATE.v  file

`default_nettype none

`include "CORTEZ_REGPOOL.vh"

// Verilog does support neither interfaces nor typedef'd data. This version flattens all
module CORTEZ_REGPOOL (
    // Clock
    input wire ACLK,
    // Active-low synchronous reset
    input wire ARESETN,
    // AXI interface
    input wire [31:0] AWADDR,
    input wire [2:0] AWPROT,
    input wire AWVALID,
    output wire AWREADY,
    input wire [7:0] WDATA,
    input wire [0:0] WSTRB,
    input wire WVALID,
    output wire WREADY,
    output wire [1:0] BRESP,
    output wire BVALID,
    input wire BREADY,
    input wire [31:0] ARADDR,
    input wire [2:0] ARPROT,
    input wire ARVALID,
    output wire ARREADY,
    output wire [7:0] RDATA,
    output wire [1:0] RRESP,
    output wire RVALID,
    input wire RREADY,
    // Register bundles
    output wire [7:0] HWIF_OUT_DBUG_REG_0,
    output wire [7:0] HWIF_OUT_DBUG_REG_1,
    output wire [7:0] HWIF_OUT_DBUG_REG_2,
    output wire [7:0] HWIF_OUT_DBUG_REG_3,
    output wire [9*8-1:0] HWIF_OUT_HL_WEIGHTS_0,
    output wire [9*8-1:0] HWIF_OUT_HL_WEIGHTS_1,
    output wire [9*8-1:0] HWIF_OUT_HL_WEIGHTS_2,
    output wire [9*8-1:0] HWIF_OUT_HL_WEIGHTS_3,
    output wire [9*8-1:0] HWIF_OUT_HL_WEIGHTS_4,
    output wire [9*8-1:0] HWIF_OUT_HL_WEIGHTS_5,
    output wire [7:0] HWIF_OUT_HL_BIAS_0,
    output wire [7:0] HWIF_OUT_HL_BIAS_1,
    output wire [7:0] HWIF_OUT_HL_BIAS_2,
    output wire [7:0] HWIF_OUT_HL_BIAS_3,
    output wire [7:0] HWIF_OUT_HL_BIAS_4,
    output wire [7:0] HWIF_OUT_HL_BIAS_5,
    output wire [6*8-1:0] HWIF_OUT_OL_WEIGHTS_0,
    output wire [6*8-1:0] HWIF_OUT_OL_WEIGHTS_1,
    output wire [6*8-1:0] HWIF_OUT_OL_WEIGHTS_2,
    output wire [7:0] HWIF_OUT_OL_BIAS_0,
    output wire [7:0] HWIF_OUT_OL_BIAS_1,
    output wire [7:0] HWIF_OUT_OL_BIAS_2,
    output wire [7:0] HWIF_OUT_INPUT_GRID_0,
    output wire [7:0] HWIF_OUT_INPUT_GRID_1,
    output wire [7:0] HWIF_OUT_INPUT_GRID_2,
    output wire [7:0] HWIF_OUT_INPUT_GRID_3,
    output wire [7:0] HWIF_OUT_INPUT_GRID_4,
    output wire [7:0] HWIF_OUT_INPUT_GRID_5,
    output wire [7:0] HWIF_OUT_INPUT_GRID_6,
    output wire [7:0] HWIF_OUT_INPUT_GRID_7,
    output wire [7:0] HWIF_OUT_INPUT_GRID_8,
    input wire [7:0] HWIF_IN_OUTPUT_SOLUTION_0,
    input wire [7:0] HWIF_IN_OUTPUT_SOLUTION_1,
    input wire [7:0] HWIF_IN_OUTPUT_SOLUTION_2,
    output wire [7:0] HWIF_OUT_CORE_CTRL,
    output wire [7:0] HWIF_OUT_CORE_DEBUG_INFO,
    input wire [7:0] HWIF_IN_CORE_STATUS,
    output wire [7:0] HWIF_OUT_SEVENSEG_0,
    output wire [7:0] HWIF_OUT_SEVENSEG_1,
    output wire [7:0] HWIF_OUT_SEVENSEG_2,
    output wire [7:0] HWIF_OUT_SEVENSEG_3
);

    wire regpool_ren;
    wire [31:0] regpool_raddr;
    reg [7:0] regpool_rdata;
    reg regpool_rvalid;
    wire regpool_wen;
    reg regpool_wen_resampled;
    wire [31:0] regpool_waddr;
    wire [7:0] regpool_wdata;

    // AXI4 Lite to Native bridge
    AXIL2NATIVE #(
        .DATA_WIDTH (8),
        .ADDR_WIDTH (32)
    )
    AXIL2NATIVE_0 (
        .AXI_ACLK       (ACLK),
        .AXI_ARESETN    (ARESETN),
        .AXI_AWADDR     (AWADDR),
        .AXI_AWPROT     (AWPROT),
        .AXI_AWVALID    (AWVALID),
        .AXI_AWREADY    (AWREADY),
        .AXI_WDATA      (WDATA),
        .AXI_WSTRB      (WSTRB),
        .AXI_WVALID     (WVALID),
        .AXI_WREADY     (WREADY),
        .AXI_BRESP      (BRESP),
        .AXI_BVALID     (BVALID),
        .AXI_BREADY     (BREADY),
        .AXI_ARADDR     (ARADDR),
        .AXI_ARPROT     (ARPROT),
        .AXI_ARVALID    (ARVALID),
        .AXI_ARREADY    (ARREADY),
        .AXI_RDATA      (RDATA),
        .AXI_RRESP      (RRESP),
        .AXI_RVALID     (RVALID),
        .AXI_RREADY     (RREADY),
        .WEN            (regpool_wen),
        .WADDR          (regpool_waddr),
        .WDATA          (regpool_wdata),
        .WACK           (), // Unused
        .REN            (regpool_ren),
        .RADDR          (regpool_raddr),
        .RDATA          (regpool_rdata),
        .RVALID         (regpool_rvalid)
    );

    // Instantiate registers and declare their own signals. From a Software perspective, i.e. access
    // via the AXI4 Lite interface, Configuration registers are Write-only while Status and Delta
    // registers are Read-only

    // DBUG_REG_0: General-purpose register for debug
    reg dbug_reg_0_wreq;
    wire dbug_reg_0_wreq_filtered;
    wire [7:0] dbug_reg_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    DBUG_REG_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (dbug_reg_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (dbug_reg_0_value_out)
    );
        
    // DBUG_REG_1: General-purpose register for debug
    reg dbug_reg_1_wreq;
    wire dbug_reg_1_wreq_filtered;
    wire [7:0] dbug_reg_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    DBUG_REG_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (dbug_reg_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (dbug_reg_1_value_out)
    );
        
    // DBUG_REG_2: General-purpose register for debug
    reg dbug_reg_2_wreq;
    wire dbug_reg_2_wreq_filtered;
    wire [7:0] dbug_reg_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    DBUG_REG_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (dbug_reg_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (dbug_reg_2_value_out)
    );
        
    // DBUG_REG_3: General-purpose register for debug
    reg dbug_reg_3_wreq;
    wire dbug_reg_3_wreq_filtered;
    wire [7:0] dbug_reg_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    DBUG_REG_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (dbug_reg_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (dbug_reg_3_value_out)
    );
        
    // HL_WEIGHTS_0_0: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_0_wreq;
    wire hl_weights_0_0_wreq_filtered;
    wire [7:0] hl_weights_0_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_0_value_out)
    );
        
    // HL_WEIGHTS_0_1: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_1_wreq;
    wire hl_weights_0_1_wreq_filtered;
    wire [7:0] hl_weights_0_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_1_value_out)
    );
        
    // HL_WEIGHTS_0_2: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_2_wreq;
    wire hl_weights_0_2_wreq_filtered;
    wire [7:0] hl_weights_0_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_2_value_out)
    );
        
    // HL_WEIGHTS_0_3: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_3_wreq;
    wire hl_weights_0_3_wreq_filtered;
    wire [7:0] hl_weights_0_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_3_value_out)
    );
        
    // HL_WEIGHTS_0_4: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_4_wreq;
    wire hl_weights_0_4_wreq_filtered;
    wire [7:0] hl_weights_0_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_4_value_out)
    );
        
    // HL_WEIGHTS_0_5: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_5_wreq;
    wire hl_weights_0_5_wreq_filtered;
    wire [7:0] hl_weights_0_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_5_value_out)
    );
        
    // HL_WEIGHTS_0_6: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_6_wreq;
    wire hl_weights_0_6_wreq_filtered;
    wire [7:0] hl_weights_0_6_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_6_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_6_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_6_value_out)
    );
        
    // HL_WEIGHTS_0_7: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_7_wreq;
    wire hl_weights_0_7_wreq_filtered;
    wire [7:0] hl_weights_0_7_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_7_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_7_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_7_value_out)
    );
        
    // HL_WEIGHTS_0_8: Weights for neuron 0 of the hidden layer
    reg hl_weights_0_8_wreq;
    wire hl_weights_0_8_wreq_filtered;
    wire [7:0] hl_weights_0_8_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_0_8_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_0_8_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_0_8_value_out)
    );
        
    // HL_WEIGHTS_1_0: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_0_wreq;
    wire hl_weights_1_0_wreq_filtered;
    wire [7:0] hl_weights_1_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_0_value_out)
    );
        
    // HL_WEIGHTS_1_1: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_1_wreq;
    wire hl_weights_1_1_wreq_filtered;
    wire [7:0] hl_weights_1_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_1_value_out)
    );
        
    // HL_WEIGHTS_1_2: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_2_wreq;
    wire hl_weights_1_2_wreq_filtered;
    wire [7:0] hl_weights_1_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_2_value_out)
    );
        
    // HL_WEIGHTS_1_3: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_3_wreq;
    wire hl_weights_1_3_wreq_filtered;
    wire [7:0] hl_weights_1_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_3_value_out)
    );
        
    // HL_WEIGHTS_1_4: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_4_wreq;
    wire hl_weights_1_4_wreq_filtered;
    wire [7:0] hl_weights_1_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_4_value_out)
    );
        
    // HL_WEIGHTS_1_5: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_5_wreq;
    wire hl_weights_1_5_wreq_filtered;
    wire [7:0] hl_weights_1_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_5_value_out)
    );
        
    // HL_WEIGHTS_1_6: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_6_wreq;
    wire hl_weights_1_6_wreq_filtered;
    wire [7:0] hl_weights_1_6_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_6_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_6_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_6_value_out)
    );
        
    // HL_WEIGHTS_1_7: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_7_wreq;
    wire hl_weights_1_7_wreq_filtered;
    wire [7:0] hl_weights_1_7_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_7_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_7_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_7_value_out)
    );
        
    // HL_WEIGHTS_1_8: Weights for neuron 1 of the hidden layer
    reg hl_weights_1_8_wreq;
    wire hl_weights_1_8_wreq_filtered;
    wire [7:0] hl_weights_1_8_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_1_8_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_1_8_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_1_8_value_out)
    );
        
    // HL_WEIGHTS_2_0: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_0_wreq;
    wire hl_weights_2_0_wreq_filtered;
    wire [7:0] hl_weights_2_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_0_value_out)
    );
        
    // HL_WEIGHTS_2_1: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_1_wreq;
    wire hl_weights_2_1_wreq_filtered;
    wire [7:0] hl_weights_2_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_1_value_out)
    );
        
    // HL_WEIGHTS_2_2: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_2_wreq;
    wire hl_weights_2_2_wreq_filtered;
    wire [7:0] hl_weights_2_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_2_value_out)
    );
        
    // HL_WEIGHTS_2_3: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_3_wreq;
    wire hl_weights_2_3_wreq_filtered;
    wire [7:0] hl_weights_2_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_3_value_out)
    );
        
    // HL_WEIGHTS_2_4: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_4_wreq;
    wire hl_weights_2_4_wreq_filtered;
    wire [7:0] hl_weights_2_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_4_value_out)
    );
        
    // HL_WEIGHTS_2_5: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_5_wreq;
    wire hl_weights_2_5_wreq_filtered;
    wire [7:0] hl_weights_2_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_5_value_out)
    );
        
    // HL_WEIGHTS_2_6: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_6_wreq;
    wire hl_weights_2_6_wreq_filtered;
    wire [7:0] hl_weights_2_6_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_6_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_6_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_6_value_out)
    );
        
    // HL_WEIGHTS_2_7: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_7_wreq;
    wire hl_weights_2_7_wreq_filtered;
    wire [7:0] hl_weights_2_7_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_7_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_7_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_7_value_out)
    );
        
    // HL_WEIGHTS_2_8: Weights for neuron 2 of the hidden layer
    reg hl_weights_2_8_wreq;
    wire hl_weights_2_8_wreq_filtered;
    wire [7:0] hl_weights_2_8_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_2_8_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_2_8_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_2_8_value_out)
    );
        
    // HL_WEIGHTS_3_0: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_0_wreq;
    wire hl_weights_3_0_wreq_filtered;
    wire [7:0] hl_weights_3_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_0_value_out)
    );
        
    // HL_WEIGHTS_3_1: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_1_wreq;
    wire hl_weights_3_1_wreq_filtered;
    wire [7:0] hl_weights_3_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_1_value_out)
    );
        
    // HL_WEIGHTS_3_2: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_2_wreq;
    wire hl_weights_3_2_wreq_filtered;
    wire [7:0] hl_weights_3_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_2_value_out)
    );
        
    // HL_WEIGHTS_3_3: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_3_wreq;
    wire hl_weights_3_3_wreq_filtered;
    wire [7:0] hl_weights_3_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_3_value_out)
    );
        
    // HL_WEIGHTS_3_4: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_4_wreq;
    wire hl_weights_3_4_wreq_filtered;
    wire [7:0] hl_weights_3_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_4_value_out)
    );
        
    // HL_WEIGHTS_3_5: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_5_wreq;
    wire hl_weights_3_5_wreq_filtered;
    wire [7:0] hl_weights_3_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_5_value_out)
    );
        
    // HL_WEIGHTS_3_6: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_6_wreq;
    wire hl_weights_3_6_wreq_filtered;
    wire [7:0] hl_weights_3_6_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_6_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_6_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_6_value_out)
    );
        
    // HL_WEIGHTS_3_7: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_7_wreq;
    wire hl_weights_3_7_wreq_filtered;
    wire [7:0] hl_weights_3_7_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_7_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_7_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_7_value_out)
    );
        
    // HL_WEIGHTS_3_8: Weights for neuron 3 of the hidden layer
    reg hl_weights_3_8_wreq;
    wire hl_weights_3_8_wreq_filtered;
    wire [7:0] hl_weights_3_8_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_3_8_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_3_8_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_3_8_value_out)
    );
        
    // HL_WEIGHTS_4_0: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_0_wreq;
    wire hl_weights_4_0_wreq_filtered;
    wire [7:0] hl_weights_4_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_0_value_out)
    );
        
    // HL_WEIGHTS_4_1: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_1_wreq;
    wire hl_weights_4_1_wreq_filtered;
    wire [7:0] hl_weights_4_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_1_value_out)
    );
        
    // HL_WEIGHTS_4_2: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_2_wreq;
    wire hl_weights_4_2_wreq_filtered;
    wire [7:0] hl_weights_4_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_2_value_out)
    );
        
    // HL_WEIGHTS_4_3: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_3_wreq;
    wire hl_weights_4_3_wreq_filtered;
    wire [7:0] hl_weights_4_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_3_value_out)
    );
        
    // HL_WEIGHTS_4_4: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_4_wreq;
    wire hl_weights_4_4_wreq_filtered;
    wire [7:0] hl_weights_4_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_4_value_out)
    );
        
    // HL_WEIGHTS_4_5: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_5_wreq;
    wire hl_weights_4_5_wreq_filtered;
    wire [7:0] hl_weights_4_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_5_value_out)
    );
        
    // HL_WEIGHTS_4_6: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_6_wreq;
    wire hl_weights_4_6_wreq_filtered;
    wire [7:0] hl_weights_4_6_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_6_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_6_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_6_value_out)
    );
        
    // HL_WEIGHTS_4_7: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_7_wreq;
    wire hl_weights_4_7_wreq_filtered;
    wire [7:0] hl_weights_4_7_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_7_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_7_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_7_value_out)
    );
        
    // HL_WEIGHTS_4_8: Weights for neuron 4 of the hidden layer
    reg hl_weights_4_8_wreq;
    wire hl_weights_4_8_wreq_filtered;
    wire [7:0] hl_weights_4_8_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_4_8_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_4_8_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_4_8_value_out)
    );
        
    // HL_WEIGHTS_5_0: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_0_wreq;
    wire hl_weights_5_0_wreq_filtered;
    wire [7:0] hl_weights_5_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_0_value_out)
    );
        
    // HL_WEIGHTS_5_1: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_1_wreq;
    wire hl_weights_5_1_wreq_filtered;
    wire [7:0] hl_weights_5_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_1_value_out)
    );
        
    // HL_WEIGHTS_5_2: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_2_wreq;
    wire hl_weights_5_2_wreq_filtered;
    wire [7:0] hl_weights_5_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_2_value_out)
    );
        
    // HL_WEIGHTS_5_3: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_3_wreq;
    wire hl_weights_5_3_wreq_filtered;
    wire [7:0] hl_weights_5_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_3_value_out)
    );
        
    // HL_WEIGHTS_5_4: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_4_wreq;
    wire hl_weights_5_4_wreq_filtered;
    wire [7:0] hl_weights_5_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_4_value_out)
    );
        
    // HL_WEIGHTS_5_5: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_5_wreq;
    wire hl_weights_5_5_wreq_filtered;
    wire [7:0] hl_weights_5_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_5_value_out)
    );
        
    // HL_WEIGHTS_5_6: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_6_wreq;
    wire hl_weights_5_6_wreq_filtered;
    wire [7:0] hl_weights_5_6_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_6_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_6_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_6_value_out)
    );
        
    // HL_WEIGHTS_5_7: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_7_wreq;
    wire hl_weights_5_7_wreq_filtered;
    wire [7:0] hl_weights_5_7_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_7_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_7_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_7_value_out)
    );
        
    // HL_WEIGHTS_5_8: Weights for neuron 5 of the hidden layer
    reg hl_weights_5_8_wreq;
    wire hl_weights_5_8_wreq_filtered;
    wire [7:0] hl_weights_5_8_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_WEIGHTS_5_8_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_weights_5_8_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_weights_5_8_value_out)
    );
        
    // HL_BIAS_0: Bias for neuron 0 of the hidden layer
    reg hl_bias_0_wreq;
    wire hl_bias_0_wreq_filtered;
    wire [7:0] hl_bias_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_BIAS_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_bias_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_bias_0_value_out)
    );
        
    // HL_BIAS_1: Bias for neuron 1 of the hidden layer
    reg hl_bias_1_wreq;
    wire hl_bias_1_wreq_filtered;
    wire [7:0] hl_bias_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_BIAS_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_bias_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_bias_1_value_out)
    );
        
    // HL_BIAS_2: Bias for neuron 2 of the hidden layer
    reg hl_bias_2_wreq;
    wire hl_bias_2_wreq_filtered;
    wire [7:0] hl_bias_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_BIAS_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_bias_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_bias_2_value_out)
    );
        
    // HL_BIAS_3: Bias for neuron 3 of the hidden layer
    reg hl_bias_3_wreq;
    wire hl_bias_3_wreq_filtered;
    wire [7:0] hl_bias_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_BIAS_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_bias_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_bias_3_value_out)
    );
        
    // HL_BIAS_4: Bias for neuron 4 of the hidden layer
    reg hl_bias_4_wreq;
    wire hl_bias_4_wreq_filtered;
    wire [7:0] hl_bias_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_BIAS_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_bias_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_bias_4_value_out)
    );
        
    // HL_BIAS_5: Bias for neuron 5 of the hidden layer
    reg hl_bias_5_wreq;
    wire hl_bias_5_wreq_filtered;
    wire [7:0] hl_bias_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    HL_BIAS_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (hl_bias_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (hl_bias_5_value_out)
    );
        
    // OL_WEIGHTS_0_0: Weights for neuron 0 of the output layer
    reg ol_weights_0_0_wreq;
    wire ol_weights_0_0_wreq_filtered;
    wire [7:0] ol_weights_0_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_0_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_0_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_0_0_value_out)
    );
        
    // OL_WEIGHTS_0_1: Weights for neuron 0 of the output layer
    reg ol_weights_0_1_wreq;
    wire ol_weights_0_1_wreq_filtered;
    wire [7:0] ol_weights_0_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_0_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_0_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_0_1_value_out)
    );
        
    // OL_WEIGHTS_0_2: Weights for neuron 0 of the output layer
    reg ol_weights_0_2_wreq;
    wire ol_weights_0_2_wreq_filtered;
    wire [7:0] ol_weights_0_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_0_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_0_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_0_2_value_out)
    );
        
    // OL_WEIGHTS_0_3: Weights for neuron 0 of the output layer
    reg ol_weights_0_3_wreq;
    wire ol_weights_0_3_wreq_filtered;
    wire [7:0] ol_weights_0_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_0_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_0_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_0_3_value_out)
    );
        
    // OL_WEIGHTS_0_4: Weights for neuron 0 of the output layer
    reg ol_weights_0_4_wreq;
    wire ol_weights_0_4_wreq_filtered;
    wire [7:0] ol_weights_0_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_0_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_0_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_0_4_value_out)
    );
        
    // OL_WEIGHTS_0_5: Weights for neuron 0 of the output layer
    reg ol_weights_0_5_wreq;
    wire ol_weights_0_5_wreq_filtered;
    wire [7:0] ol_weights_0_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_0_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_0_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_0_5_value_out)
    );
        
    // OL_WEIGHTS_1_0: Weights for neuron 1 of the output layer
    reg ol_weights_1_0_wreq;
    wire ol_weights_1_0_wreq_filtered;
    wire [7:0] ol_weights_1_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_1_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_1_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_1_0_value_out)
    );
        
    // OL_WEIGHTS_1_1: Weights for neuron 1 of the output layer
    reg ol_weights_1_1_wreq;
    wire ol_weights_1_1_wreq_filtered;
    wire [7:0] ol_weights_1_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_1_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_1_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_1_1_value_out)
    );
        
    // OL_WEIGHTS_1_2: Weights for neuron 1 of the output layer
    reg ol_weights_1_2_wreq;
    wire ol_weights_1_2_wreq_filtered;
    wire [7:0] ol_weights_1_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_1_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_1_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_1_2_value_out)
    );
        
    // OL_WEIGHTS_1_3: Weights for neuron 1 of the output layer
    reg ol_weights_1_3_wreq;
    wire ol_weights_1_3_wreq_filtered;
    wire [7:0] ol_weights_1_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_1_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_1_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_1_3_value_out)
    );
        
    // OL_WEIGHTS_1_4: Weights for neuron 1 of the output layer
    reg ol_weights_1_4_wreq;
    wire ol_weights_1_4_wreq_filtered;
    wire [7:0] ol_weights_1_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_1_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_1_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_1_4_value_out)
    );
        
    // OL_WEIGHTS_1_5: Weights for neuron 1 of the output layer
    reg ol_weights_1_5_wreq;
    wire ol_weights_1_5_wreq_filtered;
    wire [7:0] ol_weights_1_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_1_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_1_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_1_5_value_out)
    );
        
    // OL_WEIGHTS_2_0: Weights for neuron 2 of the output layer
    reg ol_weights_2_0_wreq;
    wire ol_weights_2_0_wreq_filtered;
    wire [7:0] ol_weights_2_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_2_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_2_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_2_0_value_out)
    );
        
    // OL_WEIGHTS_2_1: Weights for neuron 2 of the output layer
    reg ol_weights_2_1_wreq;
    wire ol_weights_2_1_wreq_filtered;
    wire [7:0] ol_weights_2_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_2_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_2_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_2_1_value_out)
    );
        
    // OL_WEIGHTS_2_2: Weights for neuron 2 of the output layer
    reg ol_weights_2_2_wreq;
    wire ol_weights_2_2_wreq_filtered;
    wire [7:0] ol_weights_2_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_2_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_2_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_2_2_value_out)
    );
        
    // OL_WEIGHTS_2_3: Weights for neuron 2 of the output layer
    reg ol_weights_2_3_wreq;
    wire ol_weights_2_3_wreq_filtered;
    wire [7:0] ol_weights_2_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_2_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_2_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_2_3_value_out)
    );
        
    // OL_WEIGHTS_2_4: Weights for neuron 2 of the output layer
    reg ol_weights_2_4_wreq;
    wire ol_weights_2_4_wreq_filtered;
    wire [7:0] ol_weights_2_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_2_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_2_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_2_4_value_out)
    );
        
    // OL_WEIGHTS_2_5: Weights for neuron 2 of the output layer
    reg ol_weights_2_5_wreq;
    wire ol_weights_2_5_wreq_filtered;
    wire [7:0] ol_weights_2_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_WEIGHTS_2_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_weights_2_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_weights_2_5_value_out)
    );
        
    // OL_BIAS_0: Bias for neuron 0 of the output layer
    reg ol_bias_0_wreq;
    wire ol_bias_0_wreq_filtered;
    wire [7:0] ol_bias_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_BIAS_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_bias_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_bias_0_value_out)
    );
        
    // OL_BIAS_1: Bias for neuron 1 of the output layer
    reg ol_bias_1_wreq;
    wire ol_bias_1_wreq_filtered;
    wire [7:0] ol_bias_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_BIAS_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_bias_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_bias_1_value_out)
    );
        
    // OL_BIAS_2: Bias for neuron 2 of the output layer
    reg ol_bias_2_wreq;
    wire ol_bias_2_wreq_filtered;
    wire [7:0] ol_bias_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OL_BIAS_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (ol_bias_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (ol_bias_2_value_out)
    );
        
    // INPUT_GRID_0: Pixel 0 of the input character
    reg input_grid_0_wreq;
    wire input_grid_0_wreq_filtered;
    wire [7:0] input_grid_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_0_value_out)
    );
        
    // INPUT_GRID_1: Pixel 1 of the input character
    reg input_grid_1_wreq;
    wire input_grid_1_wreq_filtered;
    wire [7:0] input_grid_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_1_value_out)
    );
        
    // INPUT_GRID_2: Pixel 2 of the input character
    reg input_grid_2_wreq;
    wire input_grid_2_wreq_filtered;
    wire [7:0] input_grid_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_2_value_out)
    );
        
    // INPUT_GRID_3: Pixel 3 of the input character
    reg input_grid_3_wreq;
    wire input_grid_3_wreq_filtered;
    wire [7:0] input_grid_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_3_value_out)
    );
        
    // INPUT_GRID_4: Pixel 4 of the input character
    reg input_grid_4_wreq;
    wire input_grid_4_wreq_filtered;
    wire [7:0] input_grid_4_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_4_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_4_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_4_value_out)
    );
        
    // INPUT_GRID_5: Pixel 5 of the input character
    reg input_grid_5_wreq;
    wire input_grid_5_wreq_filtered;
    wire [7:0] input_grid_5_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_5_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_5_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_5_value_out)
    );
        
    // INPUT_GRID_6: Pixel 6 of the input character
    reg input_grid_6_wreq;
    wire input_grid_6_wreq_filtered;
    wire [7:0] input_grid_6_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_6_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_6_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_6_value_out)
    );
        
    // INPUT_GRID_7: Pixel 7 of the input character
    reg input_grid_7_wreq;
    wire input_grid_7_wreq_filtered;
    wire [7:0] input_grid_7_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_7_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_7_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_7_value_out)
    );
        
    // INPUT_GRID_8: Pixel 8 of the input character
    reg input_grid_8_wreq;
    wire input_grid_8_wreq_filtered;
    wire [7:0] input_grid_8_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    INPUT_GRID_8_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (input_grid_8_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (input_grid_8_value_out)
    );
        
    // OUTPUT_SOLUTION_0: Digit 0 of the output solution
    wire [7:0] output_solution_0_value_in;
    wire [7:0] output_solution_0_value_out;
    RO_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OUTPUT_SOLUTION_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .VALUE_IN   (output_solution_0_value_in),
        .VALUE_OUT  (output_solution_0_value_out)
    );
        
    // OUTPUT_SOLUTION_1: Digit 1 of the output solution
    wire [7:0] output_solution_1_value_in;
    wire [7:0] output_solution_1_value_out;
    RO_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OUTPUT_SOLUTION_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .VALUE_IN   (output_solution_1_value_in),
        .VALUE_OUT  (output_solution_1_value_out)
    );
        
    // OUTPUT_SOLUTION_2: Digit 2 of the output solution
    wire [7:0] output_solution_2_value_in;
    wire [7:0] output_solution_2_value_out;
    RO_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    OUTPUT_SOLUTION_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .VALUE_IN   (output_solution_2_value_in),
        .VALUE_OUT  (output_solution_2_value_out)
    );
        
    // CORE_CTRL: Core control register
    reg core_ctrl_wreq;
    wire core_ctrl_wreq_filtered;
    wire [7:0] core_ctrl_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    CORE_CTRL_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (core_ctrl_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (core_ctrl_value_out)
    );
        
    // CORE_DEBUG_INFO: Firmware-initiated debug information
    reg core_debug_info_wreq;
    wire core_debug_info_wreq_filtered;
    wire [7:0] core_debug_info_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    CORE_DEBUG_INFO_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (core_debug_info_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (core_debug_info_value_out)
    );
        
    // CORE_STATUS: Core status register
    wire [7:0] core_status_value_in;
    wire [7:0] core_status_value_out;
    RO_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    CORE_STATUS_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .VALUE_IN   (core_status_value_in),
        .VALUE_OUT  (core_status_value_out)
    );
        
    // SEVENSEG_0: 7-segments display contents: .gfedcba
    reg sevenseg_0_wreq;
    wire sevenseg_0_wreq_filtered;
    wire [7:0] sevenseg_0_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    SEVENSEG_0_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (sevenseg_0_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (sevenseg_0_value_out)
    );
        
    // SEVENSEG_1: 7-segments display contents: .gfedcba
    reg sevenseg_1_wreq;
    wire sevenseg_1_wreq_filtered;
    wire [7:0] sevenseg_1_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    SEVENSEG_1_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (sevenseg_1_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (sevenseg_1_value_out)
    );
        
    // SEVENSEG_2: 7-segments display contents: .gfedcba
    reg sevenseg_2_wreq;
    wire sevenseg_2_wreq_filtered;
    wire [7:0] sevenseg_2_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    SEVENSEG_2_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (sevenseg_2_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (sevenseg_2_value_out)
    );
        
    // SEVENSEG_3: 7-segments display contents: .gfedcba
    reg sevenseg_3_wreq;
    wire sevenseg_3_wreq_filtered;
    wire [7:0] sevenseg_3_value_out;
    RW_REG #(
        .DATA_WIDTH (8),
        .HAS_RESET  (1)
    )
    SEVENSEG_3_REG (
        .CLK        (ACLK),
        .RSTN       (ARESETN),
        .WEN        (sevenseg_3_wreq_filtered),
        .VALUE_IN   (regpool_wdata),
        .VALUE_OUT  (sevenseg_3_value_out)
    );
        
    // Write decoder
    always @(posedge ACLK) begin
        dbug_reg_0_wreq <= 1'b0;
        dbug_reg_1_wreq <= 1'b0;
        dbug_reg_2_wreq <= 1'b0;
        dbug_reg_3_wreq <= 1'b0;
        hl_weights_0_0_wreq <= 1'b0;
        hl_weights_0_1_wreq <= 1'b0;
        hl_weights_0_2_wreq <= 1'b0;
        hl_weights_0_3_wreq <= 1'b0;
        hl_weights_0_4_wreq <= 1'b0;
        hl_weights_0_5_wreq <= 1'b0;
        hl_weights_0_6_wreq <= 1'b0;
        hl_weights_0_7_wreq <= 1'b0;
        hl_weights_0_8_wreq <= 1'b0;
        hl_weights_1_0_wreq <= 1'b0;
        hl_weights_1_1_wreq <= 1'b0;
        hl_weights_1_2_wreq <= 1'b0;
        hl_weights_1_3_wreq <= 1'b0;
        hl_weights_1_4_wreq <= 1'b0;
        hl_weights_1_5_wreq <= 1'b0;
        hl_weights_1_6_wreq <= 1'b0;
        hl_weights_1_7_wreq <= 1'b0;
        hl_weights_1_8_wreq <= 1'b0;
        hl_weights_2_0_wreq <= 1'b0;
        hl_weights_2_1_wreq <= 1'b0;
        hl_weights_2_2_wreq <= 1'b0;
        hl_weights_2_3_wreq <= 1'b0;
        hl_weights_2_4_wreq <= 1'b0;
        hl_weights_2_5_wreq <= 1'b0;
        hl_weights_2_6_wreq <= 1'b0;
        hl_weights_2_7_wreq <= 1'b0;
        hl_weights_2_8_wreq <= 1'b0;
        hl_weights_3_0_wreq <= 1'b0;
        hl_weights_3_1_wreq <= 1'b0;
        hl_weights_3_2_wreq <= 1'b0;
        hl_weights_3_3_wreq <= 1'b0;
        hl_weights_3_4_wreq <= 1'b0;
        hl_weights_3_5_wreq <= 1'b0;
        hl_weights_3_6_wreq <= 1'b0;
        hl_weights_3_7_wreq <= 1'b0;
        hl_weights_3_8_wreq <= 1'b0;
        hl_weights_4_0_wreq <= 1'b0;
        hl_weights_4_1_wreq <= 1'b0;
        hl_weights_4_2_wreq <= 1'b0;
        hl_weights_4_3_wreq <= 1'b0;
        hl_weights_4_4_wreq <= 1'b0;
        hl_weights_4_5_wreq <= 1'b0;
        hl_weights_4_6_wreq <= 1'b0;
        hl_weights_4_7_wreq <= 1'b0;
        hl_weights_4_8_wreq <= 1'b0;
        hl_weights_5_0_wreq <= 1'b0;
        hl_weights_5_1_wreq <= 1'b0;
        hl_weights_5_2_wreq <= 1'b0;
        hl_weights_5_3_wreq <= 1'b0;
        hl_weights_5_4_wreq <= 1'b0;
        hl_weights_5_5_wreq <= 1'b0;
        hl_weights_5_6_wreq <= 1'b0;
        hl_weights_5_7_wreq <= 1'b0;
        hl_weights_5_8_wreq <= 1'b0;
        hl_bias_0_wreq <= 1'b0;
        hl_bias_1_wreq <= 1'b0;
        hl_bias_2_wreq <= 1'b0;
        hl_bias_3_wreq <= 1'b0;
        hl_bias_4_wreq <= 1'b0;
        hl_bias_5_wreq <= 1'b0;
        ol_weights_0_0_wreq <= 1'b0;
        ol_weights_0_1_wreq <= 1'b0;
        ol_weights_0_2_wreq <= 1'b0;
        ol_weights_0_3_wreq <= 1'b0;
        ol_weights_0_4_wreq <= 1'b0;
        ol_weights_0_5_wreq <= 1'b0;
        ol_weights_1_0_wreq <= 1'b0;
        ol_weights_1_1_wreq <= 1'b0;
        ol_weights_1_2_wreq <= 1'b0;
        ol_weights_1_3_wreq <= 1'b0;
        ol_weights_1_4_wreq <= 1'b0;
        ol_weights_1_5_wreq <= 1'b0;
        ol_weights_2_0_wreq <= 1'b0;
        ol_weights_2_1_wreq <= 1'b0;
        ol_weights_2_2_wreq <= 1'b0;
        ol_weights_2_3_wreq <= 1'b0;
        ol_weights_2_4_wreq <= 1'b0;
        ol_weights_2_5_wreq <= 1'b0;
        ol_bias_0_wreq <= 1'b0;
        ol_bias_1_wreq <= 1'b0;
        ol_bias_2_wreq <= 1'b0;
        input_grid_0_wreq <= 1'b0;
        input_grid_1_wreq <= 1'b0;
        input_grid_2_wreq <= 1'b0;
        input_grid_3_wreq <= 1'b0;
        input_grid_4_wreq <= 1'b0;
        input_grid_5_wreq <= 1'b0;
        input_grid_6_wreq <= 1'b0;
        input_grid_7_wreq <= 1'b0;
        input_grid_8_wreq <= 1'b0;
        core_ctrl_wreq <= 1'b0;
        core_debug_info_wreq <= 1'b0;
        sevenseg_0_wreq <= 1'b0;
        sevenseg_1_wreq <= 1'b0;
        sevenseg_2_wreq <= 1'b0;
        sevenseg_3_wreq <= 1'b0;

        case(regpool_waddr)
            `DBUG_REG_0_OFFSET : begin dbug_reg_0_wreq <= 1'b1; end
            `DBUG_REG_1_OFFSET : begin dbug_reg_1_wreq <= 1'b1; end
            `DBUG_REG_2_OFFSET : begin dbug_reg_2_wreq <= 1'b1; end
            `DBUG_REG_3_OFFSET : begin dbug_reg_3_wreq <= 1'b1; end
            `HL_WEIGHTS_0_0_OFFSET : begin hl_weights_0_0_wreq <= 1'b1; end
            `HL_WEIGHTS_0_1_OFFSET : begin hl_weights_0_1_wreq <= 1'b1; end
            `HL_WEIGHTS_0_2_OFFSET : begin hl_weights_0_2_wreq <= 1'b1; end
            `HL_WEIGHTS_0_3_OFFSET : begin hl_weights_0_3_wreq <= 1'b1; end
            `HL_WEIGHTS_0_4_OFFSET : begin hl_weights_0_4_wreq <= 1'b1; end
            `HL_WEIGHTS_0_5_OFFSET : begin hl_weights_0_5_wreq <= 1'b1; end
            `HL_WEIGHTS_0_6_OFFSET : begin hl_weights_0_6_wreq <= 1'b1; end
            `HL_WEIGHTS_0_7_OFFSET : begin hl_weights_0_7_wreq <= 1'b1; end
            `HL_WEIGHTS_0_8_OFFSET : begin hl_weights_0_8_wreq <= 1'b1; end
            `HL_WEIGHTS_1_0_OFFSET : begin hl_weights_1_0_wreq <= 1'b1; end
            `HL_WEIGHTS_1_1_OFFSET : begin hl_weights_1_1_wreq <= 1'b1; end
            `HL_WEIGHTS_1_2_OFFSET : begin hl_weights_1_2_wreq <= 1'b1; end
            `HL_WEIGHTS_1_3_OFFSET : begin hl_weights_1_3_wreq <= 1'b1; end
            `HL_WEIGHTS_1_4_OFFSET : begin hl_weights_1_4_wreq <= 1'b1; end
            `HL_WEIGHTS_1_5_OFFSET : begin hl_weights_1_5_wreq <= 1'b1; end
            `HL_WEIGHTS_1_6_OFFSET : begin hl_weights_1_6_wreq <= 1'b1; end
            `HL_WEIGHTS_1_7_OFFSET : begin hl_weights_1_7_wreq <= 1'b1; end
            `HL_WEIGHTS_1_8_OFFSET : begin hl_weights_1_8_wreq <= 1'b1; end
            `HL_WEIGHTS_2_0_OFFSET : begin hl_weights_2_0_wreq <= 1'b1; end
            `HL_WEIGHTS_2_1_OFFSET : begin hl_weights_2_1_wreq <= 1'b1; end
            `HL_WEIGHTS_2_2_OFFSET : begin hl_weights_2_2_wreq <= 1'b1; end
            `HL_WEIGHTS_2_3_OFFSET : begin hl_weights_2_3_wreq <= 1'b1; end
            `HL_WEIGHTS_2_4_OFFSET : begin hl_weights_2_4_wreq <= 1'b1; end
            `HL_WEIGHTS_2_5_OFFSET : begin hl_weights_2_5_wreq <= 1'b1; end
            `HL_WEIGHTS_2_6_OFFSET : begin hl_weights_2_6_wreq <= 1'b1; end
            `HL_WEIGHTS_2_7_OFFSET : begin hl_weights_2_7_wreq <= 1'b1; end
            `HL_WEIGHTS_2_8_OFFSET : begin hl_weights_2_8_wreq <= 1'b1; end
            `HL_WEIGHTS_3_0_OFFSET : begin hl_weights_3_0_wreq <= 1'b1; end
            `HL_WEIGHTS_3_1_OFFSET : begin hl_weights_3_1_wreq <= 1'b1; end
            `HL_WEIGHTS_3_2_OFFSET : begin hl_weights_3_2_wreq <= 1'b1; end
            `HL_WEIGHTS_3_3_OFFSET : begin hl_weights_3_3_wreq <= 1'b1; end
            `HL_WEIGHTS_3_4_OFFSET : begin hl_weights_3_4_wreq <= 1'b1; end
            `HL_WEIGHTS_3_5_OFFSET : begin hl_weights_3_5_wreq <= 1'b1; end
            `HL_WEIGHTS_3_6_OFFSET : begin hl_weights_3_6_wreq <= 1'b1; end
            `HL_WEIGHTS_3_7_OFFSET : begin hl_weights_3_7_wreq <= 1'b1; end
            `HL_WEIGHTS_3_8_OFFSET : begin hl_weights_3_8_wreq <= 1'b1; end
            `HL_WEIGHTS_4_0_OFFSET : begin hl_weights_4_0_wreq <= 1'b1; end
            `HL_WEIGHTS_4_1_OFFSET : begin hl_weights_4_1_wreq <= 1'b1; end
            `HL_WEIGHTS_4_2_OFFSET : begin hl_weights_4_2_wreq <= 1'b1; end
            `HL_WEIGHTS_4_3_OFFSET : begin hl_weights_4_3_wreq <= 1'b1; end
            `HL_WEIGHTS_4_4_OFFSET : begin hl_weights_4_4_wreq <= 1'b1; end
            `HL_WEIGHTS_4_5_OFFSET : begin hl_weights_4_5_wreq <= 1'b1; end
            `HL_WEIGHTS_4_6_OFFSET : begin hl_weights_4_6_wreq <= 1'b1; end
            `HL_WEIGHTS_4_7_OFFSET : begin hl_weights_4_7_wreq <= 1'b1; end
            `HL_WEIGHTS_4_8_OFFSET : begin hl_weights_4_8_wreq <= 1'b1; end
            `HL_WEIGHTS_5_0_OFFSET : begin hl_weights_5_0_wreq <= 1'b1; end
            `HL_WEIGHTS_5_1_OFFSET : begin hl_weights_5_1_wreq <= 1'b1; end
            `HL_WEIGHTS_5_2_OFFSET : begin hl_weights_5_2_wreq <= 1'b1; end
            `HL_WEIGHTS_5_3_OFFSET : begin hl_weights_5_3_wreq <= 1'b1; end
            `HL_WEIGHTS_5_4_OFFSET : begin hl_weights_5_4_wreq <= 1'b1; end
            `HL_WEIGHTS_5_5_OFFSET : begin hl_weights_5_5_wreq <= 1'b1; end
            `HL_WEIGHTS_5_6_OFFSET : begin hl_weights_5_6_wreq <= 1'b1; end
            `HL_WEIGHTS_5_7_OFFSET : begin hl_weights_5_7_wreq <= 1'b1; end
            `HL_WEIGHTS_5_8_OFFSET : begin hl_weights_5_8_wreq <= 1'b1; end
            `HL_BIAS_0_OFFSET : begin hl_bias_0_wreq <= 1'b1; end
            `HL_BIAS_1_OFFSET : begin hl_bias_1_wreq <= 1'b1; end
            `HL_BIAS_2_OFFSET : begin hl_bias_2_wreq <= 1'b1; end
            `HL_BIAS_3_OFFSET : begin hl_bias_3_wreq <= 1'b1; end
            `HL_BIAS_4_OFFSET : begin hl_bias_4_wreq <= 1'b1; end
            `HL_BIAS_5_OFFSET : begin hl_bias_5_wreq <= 1'b1; end
            `OL_WEIGHTS_0_0_OFFSET : begin ol_weights_0_0_wreq <= 1'b1; end
            `OL_WEIGHTS_0_1_OFFSET : begin ol_weights_0_1_wreq <= 1'b1; end
            `OL_WEIGHTS_0_2_OFFSET : begin ol_weights_0_2_wreq <= 1'b1; end
            `OL_WEIGHTS_0_3_OFFSET : begin ol_weights_0_3_wreq <= 1'b1; end
            `OL_WEIGHTS_0_4_OFFSET : begin ol_weights_0_4_wreq <= 1'b1; end
            `OL_WEIGHTS_0_5_OFFSET : begin ol_weights_0_5_wreq <= 1'b1; end
            `OL_WEIGHTS_1_0_OFFSET : begin ol_weights_1_0_wreq <= 1'b1; end
            `OL_WEIGHTS_1_1_OFFSET : begin ol_weights_1_1_wreq <= 1'b1; end
            `OL_WEIGHTS_1_2_OFFSET : begin ol_weights_1_2_wreq <= 1'b1; end
            `OL_WEIGHTS_1_3_OFFSET : begin ol_weights_1_3_wreq <= 1'b1; end
            `OL_WEIGHTS_1_4_OFFSET : begin ol_weights_1_4_wreq <= 1'b1; end
            `OL_WEIGHTS_1_5_OFFSET : begin ol_weights_1_5_wreq <= 1'b1; end
            `OL_WEIGHTS_2_0_OFFSET : begin ol_weights_2_0_wreq <= 1'b1; end
            `OL_WEIGHTS_2_1_OFFSET : begin ol_weights_2_1_wreq <= 1'b1; end
            `OL_WEIGHTS_2_2_OFFSET : begin ol_weights_2_2_wreq <= 1'b1; end
            `OL_WEIGHTS_2_3_OFFSET : begin ol_weights_2_3_wreq <= 1'b1; end
            `OL_WEIGHTS_2_4_OFFSET : begin ol_weights_2_4_wreq <= 1'b1; end
            `OL_WEIGHTS_2_5_OFFSET : begin ol_weights_2_5_wreq <= 1'b1; end
            `OL_BIAS_0_OFFSET : begin ol_bias_0_wreq <= 1'b1; end
            `OL_BIAS_1_OFFSET : begin ol_bias_1_wreq <= 1'b1; end
            `OL_BIAS_2_OFFSET : begin ol_bias_2_wreq <= 1'b1; end
            `INPUT_GRID_0_OFFSET : begin input_grid_0_wreq <= 1'b1; end
            `INPUT_GRID_1_OFFSET : begin input_grid_1_wreq <= 1'b1; end
            `INPUT_GRID_2_OFFSET : begin input_grid_2_wreq <= 1'b1; end
            `INPUT_GRID_3_OFFSET : begin input_grid_3_wreq <= 1'b1; end
            `INPUT_GRID_4_OFFSET : begin input_grid_4_wreq <= 1'b1; end
            `INPUT_GRID_5_OFFSET : begin input_grid_5_wreq <= 1'b1; end
            `INPUT_GRID_6_OFFSET : begin input_grid_6_wreq <= 1'b1; end
            `INPUT_GRID_7_OFFSET : begin input_grid_7_wreq <= 1'b1; end
            `INPUT_GRID_8_OFFSET : begin input_grid_8_wreq <= 1'b1; end
            `CORE_CTRL_OFFSET : begin core_ctrl_wreq <= 1'b1; end
            `CORE_DEBUG_INFO_OFFSET : begin core_debug_info_wreq <= 1'b1; end
            `SEVENSEG_0_OFFSET : begin sevenseg_0_wreq <= 1'b1; end
            `SEVENSEG_1_OFFSET : begin sevenseg_1_wreq <= 1'b1; end
            `SEVENSEG_2_OFFSET : begin sevenseg_2_wreq <= 1'b1; end
            `SEVENSEG_3_OFFSET : begin sevenseg_3_wreq <= 1'b1; end
        endcase
    end

    // Align Write enable to resampled decoder
    always @(posedge ACLK) begin
        regpool_wen_resampled <= regpool_wen;
    end

    // Filter Write enables
    assign dbug_reg_0_wreq_filtered = dbug_reg_0_wreq & regpool_wen_resampled;
    assign dbug_reg_1_wreq_filtered = dbug_reg_1_wreq & regpool_wen_resampled;
    assign dbug_reg_2_wreq_filtered = dbug_reg_2_wreq & regpool_wen_resampled;
    assign dbug_reg_3_wreq_filtered = dbug_reg_3_wreq & regpool_wen_resampled;
    assign hl_weights_0_0_wreq_filtered = hl_weights_0_0_wreq & regpool_wen_resampled;
    assign hl_weights_0_1_wreq_filtered = hl_weights_0_1_wreq & regpool_wen_resampled;
    assign hl_weights_0_2_wreq_filtered = hl_weights_0_2_wreq & regpool_wen_resampled;
    assign hl_weights_0_3_wreq_filtered = hl_weights_0_3_wreq & regpool_wen_resampled;
    assign hl_weights_0_4_wreq_filtered = hl_weights_0_4_wreq & regpool_wen_resampled;
    assign hl_weights_0_5_wreq_filtered = hl_weights_0_5_wreq & regpool_wen_resampled;
    assign hl_weights_0_6_wreq_filtered = hl_weights_0_6_wreq & regpool_wen_resampled;
    assign hl_weights_0_7_wreq_filtered = hl_weights_0_7_wreq & regpool_wen_resampled;
    assign hl_weights_0_8_wreq_filtered = hl_weights_0_8_wreq & regpool_wen_resampled;
    assign hl_weights_1_0_wreq_filtered = hl_weights_1_0_wreq & regpool_wen_resampled;
    assign hl_weights_1_1_wreq_filtered = hl_weights_1_1_wreq & regpool_wen_resampled;
    assign hl_weights_1_2_wreq_filtered = hl_weights_1_2_wreq & regpool_wen_resampled;
    assign hl_weights_1_3_wreq_filtered = hl_weights_1_3_wreq & regpool_wen_resampled;
    assign hl_weights_1_4_wreq_filtered = hl_weights_1_4_wreq & regpool_wen_resampled;
    assign hl_weights_1_5_wreq_filtered = hl_weights_1_5_wreq & regpool_wen_resampled;
    assign hl_weights_1_6_wreq_filtered = hl_weights_1_6_wreq & regpool_wen_resampled;
    assign hl_weights_1_7_wreq_filtered = hl_weights_1_7_wreq & regpool_wen_resampled;
    assign hl_weights_1_8_wreq_filtered = hl_weights_1_8_wreq & regpool_wen_resampled;
    assign hl_weights_2_0_wreq_filtered = hl_weights_2_0_wreq & regpool_wen_resampled;
    assign hl_weights_2_1_wreq_filtered = hl_weights_2_1_wreq & regpool_wen_resampled;
    assign hl_weights_2_2_wreq_filtered = hl_weights_2_2_wreq & regpool_wen_resampled;
    assign hl_weights_2_3_wreq_filtered = hl_weights_2_3_wreq & regpool_wen_resampled;
    assign hl_weights_2_4_wreq_filtered = hl_weights_2_4_wreq & regpool_wen_resampled;
    assign hl_weights_2_5_wreq_filtered = hl_weights_2_5_wreq & regpool_wen_resampled;
    assign hl_weights_2_6_wreq_filtered = hl_weights_2_6_wreq & regpool_wen_resampled;
    assign hl_weights_2_7_wreq_filtered = hl_weights_2_7_wreq & regpool_wen_resampled;
    assign hl_weights_2_8_wreq_filtered = hl_weights_2_8_wreq & regpool_wen_resampled;
    assign hl_weights_3_0_wreq_filtered = hl_weights_3_0_wreq & regpool_wen_resampled;
    assign hl_weights_3_1_wreq_filtered = hl_weights_3_1_wreq & regpool_wen_resampled;
    assign hl_weights_3_2_wreq_filtered = hl_weights_3_2_wreq & regpool_wen_resampled;
    assign hl_weights_3_3_wreq_filtered = hl_weights_3_3_wreq & regpool_wen_resampled;
    assign hl_weights_3_4_wreq_filtered = hl_weights_3_4_wreq & regpool_wen_resampled;
    assign hl_weights_3_5_wreq_filtered = hl_weights_3_5_wreq & regpool_wen_resampled;
    assign hl_weights_3_6_wreq_filtered = hl_weights_3_6_wreq & regpool_wen_resampled;
    assign hl_weights_3_7_wreq_filtered = hl_weights_3_7_wreq & regpool_wen_resampled;
    assign hl_weights_3_8_wreq_filtered = hl_weights_3_8_wreq & regpool_wen_resampled;
    assign hl_weights_4_0_wreq_filtered = hl_weights_4_0_wreq & regpool_wen_resampled;
    assign hl_weights_4_1_wreq_filtered = hl_weights_4_1_wreq & regpool_wen_resampled;
    assign hl_weights_4_2_wreq_filtered = hl_weights_4_2_wreq & regpool_wen_resampled;
    assign hl_weights_4_3_wreq_filtered = hl_weights_4_3_wreq & regpool_wen_resampled;
    assign hl_weights_4_4_wreq_filtered = hl_weights_4_4_wreq & regpool_wen_resampled;
    assign hl_weights_4_5_wreq_filtered = hl_weights_4_5_wreq & regpool_wen_resampled;
    assign hl_weights_4_6_wreq_filtered = hl_weights_4_6_wreq & regpool_wen_resampled;
    assign hl_weights_4_7_wreq_filtered = hl_weights_4_7_wreq & regpool_wen_resampled;
    assign hl_weights_4_8_wreq_filtered = hl_weights_4_8_wreq & regpool_wen_resampled;
    assign hl_weights_5_0_wreq_filtered = hl_weights_5_0_wreq & regpool_wen_resampled;
    assign hl_weights_5_1_wreq_filtered = hl_weights_5_1_wreq & regpool_wen_resampled;
    assign hl_weights_5_2_wreq_filtered = hl_weights_5_2_wreq & regpool_wen_resampled;
    assign hl_weights_5_3_wreq_filtered = hl_weights_5_3_wreq & regpool_wen_resampled;
    assign hl_weights_5_4_wreq_filtered = hl_weights_5_4_wreq & regpool_wen_resampled;
    assign hl_weights_5_5_wreq_filtered = hl_weights_5_5_wreq & regpool_wen_resampled;
    assign hl_weights_5_6_wreq_filtered = hl_weights_5_6_wreq & regpool_wen_resampled;
    assign hl_weights_5_7_wreq_filtered = hl_weights_5_7_wreq & regpool_wen_resampled;
    assign hl_weights_5_8_wreq_filtered = hl_weights_5_8_wreq & regpool_wen_resampled;
    assign hl_bias_0_wreq_filtered = hl_bias_0_wreq & regpool_wen_resampled;
    assign hl_bias_1_wreq_filtered = hl_bias_1_wreq & regpool_wen_resampled;
    assign hl_bias_2_wreq_filtered = hl_bias_2_wreq & regpool_wen_resampled;
    assign hl_bias_3_wreq_filtered = hl_bias_3_wreq & regpool_wen_resampled;
    assign hl_bias_4_wreq_filtered = hl_bias_4_wreq & regpool_wen_resampled;
    assign hl_bias_5_wreq_filtered = hl_bias_5_wreq & regpool_wen_resampled;
    assign ol_weights_0_0_wreq_filtered = ol_weights_0_0_wreq & regpool_wen_resampled;
    assign ol_weights_0_1_wreq_filtered = ol_weights_0_1_wreq & regpool_wen_resampled;
    assign ol_weights_0_2_wreq_filtered = ol_weights_0_2_wreq & regpool_wen_resampled;
    assign ol_weights_0_3_wreq_filtered = ol_weights_0_3_wreq & regpool_wen_resampled;
    assign ol_weights_0_4_wreq_filtered = ol_weights_0_4_wreq & regpool_wen_resampled;
    assign ol_weights_0_5_wreq_filtered = ol_weights_0_5_wreq & regpool_wen_resampled;
    assign ol_weights_1_0_wreq_filtered = ol_weights_1_0_wreq & regpool_wen_resampled;
    assign ol_weights_1_1_wreq_filtered = ol_weights_1_1_wreq & regpool_wen_resampled;
    assign ol_weights_1_2_wreq_filtered = ol_weights_1_2_wreq & regpool_wen_resampled;
    assign ol_weights_1_3_wreq_filtered = ol_weights_1_3_wreq & regpool_wen_resampled;
    assign ol_weights_1_4_wreq_filtered = ol_weights_1_4_wreq & regpool_wen_resampled;
    assign ol_weights_1_5_wreq_filtered = ol_weights_1_5_wreq & regpool_wen_resampled;
    assign ol_weights_2_0_wreq_filtered = ol_weights_2_0_wreq & regpool_wen_resampled;
    assign ol_weights_2_1_wreq_filtered = ol_weights_2_1_wreq & regpool_wen_resampled;
    assign ol_weights_2_2_wreq_filtered = ol_weights_2_2_wreq & regpool_wen_resampled;
    assign ol_weights_2_3_wreq_filtered = ol_weights_2_3_wreq & regpool_wen_resampled;
    assign ol_weights_2_4_wreq_filtered = ol_weights_2_4_wreq & regpool_wen_resampled;
    assign ol_weights_2_5_wreq_filtered = ol_weights_2_5_wreq & regpool_wen_resampled;
    assign ol_bias_0_wreq_filtered = ol_bias_0_wreq & regpool_wen_resampled;
    assign ol_bias_1_wreq_filtered = ol_bias_1_wreq & regpool_wen_resampled;
    assign ol_bias_2_wreq_filtered = ol_bias_2_wreq & regpool_wen_resampled;
    assign input_grid_0_wreq_filtered = input_grid_0_wreq & regpool_wen_resampled;
    assign input_grid_1_wreq_filtered = input_grid_1_wreq & regpool_wen_resampled;
    assign input_grid_2_wreq_filtered = input_grid_2_wreq & regpool_wen_resampled;
    assign input_grid_3_wreq_filtered = input_grid_3_wreq & regpool_wen_resampled;
    assign input_grid_4_wreq_filtered = input_grid_4_wreq & regpool_wen_resampled;
    assign input_grid_5_wreq_filtered = input_grid_5_wreq & regpool_wen_resampled;
    assign input_grid_6_wreq_filtered = input_grid_6_wreq & regpool_wen_resampled;
    assign input_grid_7_wreq_filtered = input_grid_7_wreq & regpool_wen_resampled;
    assign input_grid_8_wreq_filtered = input_grid_8_wreq & regpool_wen_resampled;
    assign core_ctrl_wreq_filtered = core_ctrl_wreq & regpool_wen_resampled;
    assign core_debug_info_wreq_filtered = core_debug_info_wreq & regpool_wen_resampled;
    assign sevenseg_0_wreq_filtered = sevenseg_0_wreq & regpool_wen_resampled;
    assign sevenseg_1_wreq_filtered = sevenseg_1_wreq & regpool_wen_resampled;
    assign sevenseg_2_wreq_filtered = sevenseg_2_wreq & regpool_wen_resampled;
    assign sevenseg_3_wreq_filtered = sevenseg_3_wreq & regpool_wen_resampled;

    // Create Read strobe from Read request edge
    always @(posedge ACLK) begin
        regpool_rvalid <= regpool_ren;
    end

    // Read decoder
    always @(posedge ACLK) begin
        case(regpool_raddr)
            `DBUG_REG_0_OFFSET : begin regpool_rdata <= dbug_reg_0_value_out; end
            `DBUG_REG_1_OFFSET : begin regpool_rdata <= dbug_reg_1_value_out; end
            `DBUG_REG_2_OFFSET : begin regpool_rdata <= dbug_reg_2_value_out; end
            `DBUG_REG_3_OFFSET : begin regpool_rdata <= dbug_reg_3_value_out; end
            `HL_WEIGHTS_0_0_OFFSET : begin regpool_rdata <= hl_weights_0_0_value_out; end
            `HL_WEIGHTS_0_1_OFFSET : begin regpool_rdata <= hl_weights_0_1_value_out; end
            `HL_WEIGHTS_0_2_OFFSET : begin regpool_rdata <= hl_weights_0_2_value_out; end
            `HL_WEIGHTS_0_3_OFFSET : begin regpool_rdata <= hl_weights_0_3_value_out; end
            `HL_WEIGHTS_0_4_OFFSET : begin regpool_rdata <= hl_weights_0_4_value_out; end
            `HL_WEIGHTS_0_5_OFFSET : begin regpool_rdata <= hl_weights_0_5_value_out; end
            `HL_WEIGHTS_0_6_OFFSET : begin regpool_rdata <= hl_weights_0_6_value_out; end
            `HL_WEIGHTS_0_7_OFFSET : begin regpool_rdata <= hl_weights_0_7_value_out; end
            `HL_WEIGHTS_0_8_OFFSET : begin regpool_rdata <= hl_weights_0_8_value_out; end
            `HL_WEIGHTS_1_0_OFFSET : begin regpool_rdata <= hl_weights_1_0_value_out; end
            `HL_WEIGHTS_1_1_OFFSET : begin regpool_rdata <= hl_weights_1_1_value_out; end
            `HL_WEIGHTS_1_2_OFFSET : begin regpool_rdata <= hl_weights_1_2_value_out; end
            `HL_WEIGHTS_1_3_OFFSET : begin regpool_rdata <= hl_weights_1_3_value_out; end
            `HL_WEIGHTS_1_4_OFFSET : begin regpool_rdata <= hl_weights_1_4_value_out; end
            `HL_WEIGHTS_1_5_OFFSET : begin regpool_rdata <= hl_weights_1_5_value_out; end
            `HL_WEIGHTS_1_6_OFFSET : begin regpool_rdata <= hl_weights_1_6_value_out; end
            `HL_WEIGHTS_1_7_OFFSET : begin regpool_rdata <= hl_weights_1_7_value_out; end
            `HL_WEIGHTS_1_8_OFFSET : begin regpool_rdata <= hl_weights_1_8_value_out; end
            `HL_WEIGHTS_2_0_OFFSET : begin regpool_rdata <= hl_weights_2_0_value_out; end
            `HL_WEIGHTS_2_1_OFFSET : begin regpool_rdata <= hl_weights_2_1_value_out; end
            `HL_WEIGHTS_2_2_OFFSET : begin regpool_rdata <= hl_weights_2_2_value_out; end
            `HL_WEIGHTS_2_3_OFFSET : begin regpool_rdata <= hl_weights_2_3_value_out; end
            `HL_WEIGHTS_2_4_OFFSET : begin regpool_rdata <= hl_weights_2_4_value_out; end
            `HL_WEIGHTS_2_5_OFFSET : begin regpool_rdata <= hl_weights_2_5_value_out; end
            `HL_WEIGHTS_2_6_OFFSET : begin regpool_rdata <= hl_weights_2_6_value_out; end
            `HL_WEIGHTS_2_7_OFFSET : begin regpool_rdata <= hl_weights_2_7_value_out; end
            `HL_WEIGHTS_2_8_OFFSET : begin regpool_rdata <= hl_weights_2_8_value_out; end
            `HL_WEIGHTS_3_0_OFFSET : begin regpool_rdata <= hl_weights_3_0_value_out; end
            `HL_WEIGHTS_3_1_OFFSET : begin regpool_rdata <= hl_weights_3_1_value_out; end
            `HL_WEIGHTS_3_2_OFFSET : begin regpool_rdata <= hl_weights_3_2_value_out; end
            `HL_WEIGHTS_3_3_OFFSET : begin regpool_rdata <= hl_weights_3_3_value_out; end
            `HL_WEIGHTS_3_4_OFFSET : begin regpool_rdata <= hl_weights_3_4_value_out; end
            `HL_WEIGHTS_3_5_OFFSET : begin regpool_rdata <= hl_weights_3_5_value_out; end
            `HL_WEIGHTS_3_6_OFFSET : begin regpool_rdata <= hl_weights_3_6_value_out; end
            `HL_WEIGHTS_3_7_OFFSET : begin regpool_rdata <= hl_weights_3_7_value_out; end
            `HL_WEIGHTS_3_8_OFFSET : begin regpool_rdata <= hl_weights_3_8_value_out; end
            `HL_WEIGHTS_4_0_OFFSET : begin regpool_rdata <= hl_weights_4_0_value_out; end
            `HL_WEIGHTS_4_1_OFFSET : begin regpool_rdata <= hl_weights_4_1_value_out; end
            `HL_WEIGHTS_4_2_OFFSET : begin regpool_rdata <= hl_weights_4_2_value_out; end
            `HL_WEIGHTS_4_3_OFFSET : begin regpool_rdata <= hl_weights_4_3_value_out; end
            `HL_WEIGHTS_4_4_OFFSET : begin regpool_rdata <= hl_weights_4_4_value_out; end
            `HL_WEIGHTS_4_5_OFFSET : begin regpool_rdata <= hl_weights_4_5_value_out; end
            `HL_WEIGHTS_4_6_OFFSET : begin regpool_rdata <= hl_weights_4_6_value_out; end
            `HL_WEIGHTS_4_7_OFFSET : begin regpool_rdata <= hl_weights_4_7_value_out; end
            `HL_WEIGHTS_4_8_OFFSET : begin regpool_rdata <= hl_weights_4_8_value_out; end
            `HL_WEIGHTS_5_0_OFFSET : begin regpool_rdata <= hl_weights_5_0_value_out; end
            `HL_WEIGHTS_5_1_OFFSET : begin regpool_rdata <= hl_weights_5_1_value_out; end
            `HL_WEIGHTS_5_2_OFFSET : begin regpool_rdata <= hl_weights_5_2_value_out; end
            `HL_WEIGHTS_5_3_OFFSET : begin regpool_rdata <= hl_weights_5_3_value_out; end
            `HL_WEIGHTS_5_4_OFFSET : begin regpool_rdata <= hl_weights_5_4_value_out; end
            `HL_WEIGHTS_5_5_OFFSET : begin regpool_rdata <= hl_weights_5_5_value_out; end
            `HL_WEIGHTS_5_6_OFFSET : begin regpool_rdata <= hl_weights_5_6_value_out; end
            `HL_WEIGHTS_5_7_OFFSET : begin regpool_rdata <= hl_weights_5_7_value_out; end
            `HL_WEIGHTS_5_8_OFFSET : begin regpool_rdata <= hl_weights_5_8_value_out; end
            `HL_BIAS_0_OFFSET : begin regpool_rdata <= hl_bias_0_value_out; end
            `HL_BIAS_1_OFFSET : begin regpool_rdata <= hl_bias_1_value_out; end
            `HL_BIAS_2_OFFSET : begin regpool_rdata <= hl_bias_2_value_out; end
            `HL_BIAS_3_OFFSET : begin regpool_rdata <= hl_bias_3_value_out; end
            `HL_BIAS_4_OFFSET : begin regpool_rdata <= hl_bias_4_value_out; end
            `HL_BIAS_5_OFFSET : begin regpool_rdata <= hl_bias_5_value_out; end
            `OL_WEIGHTS_0_0_OFFSET : begin regpool_rdata <= ol_weights_0_0_value_out; end
            `OL_WEIGHTS_0_1_OFFSET : begin regpool_rdata <= ol_weights_0_1_value_out; end
            `OL_WEIGHTS_0_2_OFFSET : begin regpool_rdata <= ol_weights_0_2_value_out; end
            `OL_WEIGHTS_0_3_OFFSET : begin regpool_rdata <= ol_weights_0_3_value_out; end
            `OL_WEIGHTS_0_4_OFFSET : begin regpool_rdata <= ol_weights_0_4_value_out; end
            `OL_WEIGHTS_0_5_OFFSET : begin regpool_rdata <= ol_weights_0_5_value_out; end
            `OL_WEIGHTS_1_0_OFFSET : begin regpool_rdata <= ol_weights_1_0_value_out; end
            `OL_WEIGHTS_1_1_OFFSET : begin regpool_rdata <= ol_weights_1_1_value_out; end
            `OL_WEIGHTS_1_2_OFFSET : begin regpool_rdata <= ol_weights_1_2_value_out; end
            `OL_WEIGHTS_1_3_OFFSET : begin regpool_rdata <= ol_weights_1_3_value_out; end
            `OL_WEIGHTS_1_4_OFFSET : begin regpool_rdata <= ol_weights_1_4_value_out; end
            `OL_WEIGHTS_1_5_OFFSET : begin regpool_rdata <= ol_weights_1_5_value_out; end
            `OL_WEIGHTS_2_0_OFFSET : begin regpool_rdata <= ol_weights_2_0_value_out; end
            `OL_WEIGHTS_2_1_OFFSET : begin regpool_rdata <= ol_weights_2_1_value_out; end
            `OL_WEIGHTS_2_2_OFFSET : begin regpool_rdata <= ol_weights_2_2_value_out; end
            `OL_WEIGHTS_2_3_OFFSET : begin regpool_rdata <= ol_weights_2_3_value_out; end
            `OL_WEIGHTS_2_4_OFFSET : begin regpool_rdata <= ol_weights_2_4_value_out; end
            `OL_WEIGHTS_2_5_OFFSET : begin regpool_rdata <= ol_weights_2_5_value_out; end
            `OL_BIAS_0_OFFSET : begin regpool_rdata <= ol_bias_0_value_out; end
            `OL_BIAS_1_OFFSET : begin regpool_rdata <= ol_bias_1_value_out; end
            `OL_BIAS_2_OFFSET : begin regpool_rdata <= ol_bias_2_value_out; end
            `INPUT_GRID_0_OFFSET : begin regpool_rdata <= input_grid_0_value_out; end
            `INPUT_GRID_1_OFFSET : begin regpool_rdata <= input_grid_1_value_out; end
            `INPUT_GRID_2_OFFSET : begin regpool_rdata <= input_grid_2_value_out; end
            `INPUT_GRID_3_OFFSET : begin regpool_rdata <= input_grid_3_value_out; end
            `INPUT_GRID_4_OFFSET : begin regpool_rdata <= input_grid_4_value_out; end
            `INPUT_GRID_5_OFFSET : begin regpool_rdata <= input_grid_5_value_out; end
            `INPUT_GRID_6_OFFSET : begin regpool_rdata <= input_grid_6_value_out; end
            `INPUT_GRID_7_OFFSET : begin regpool_rdata <= input_grid_7_value_out; end
            `INPUT_GRID_8_OFFSET : begin regpool_rdata <= input_grid_8_value_out; end
            `OUTPUT_SOLUTION_0_OFFSET : begin regpool_rdata <= output_solution_0_value_out; end
            `OUTPUT_SOLUTION_1_OFFSET : begin regpool_rdata <= output_solution_1_value_out; end
            `OUTPUT_SOLUTION_2_OFFSET : begin regpool_rdata <= output_solution_2_value_out; end
            `CORE_CTRL_OFFSET : begin regpool_rdata <= core_ctrl_value_out; end
            `CORE_DEBUG_INFO_OFFSET : begin regpool_rdata <= core_debug_info_value_out; end
            `CORE_STATUS_OFFSET : begin regpool_rdata <= core_status_value_out; end
            `SEVENSEG_0_OFFSET : begin regpool_rdata <= sevenseg_0_value_out; end
            `SEVENSEG_1_OFFSET : begin regpool_rdata <= sevenseg_1_value_out; end
            `SEVENSEG_2_OFFSET : begin regpool_rdata <= sevenseg_2_value_out; end
            `SEVENSEG_3_OFFSET : begin regpool_rdata <= sevenseg_3_value_out; end
            default : begin regpool_rdata <= 32'hdeadbeef; end
        endcase
    end

    // Compose and decompose CSR bundle data. Control registers (those written by the Software and
    // read by the Hardware) are put over the  HWIF_OUT_*  ports; Status registers (those written by
    // the Hardware and read by the Software) are get over the  HWIF_IN_*  ports
    assign HWIF_OUT_DBUG_REG_0 = dbug_reg_0_value_out;
    assign HWIF_OUT_DBUG_REG_1 = dbug_reg_1_value_out;
    assign HWIF_OUT_DBUG_REG_2 = dbug_reg_2_value_out;
    assign HWIF_OUT_DBUG_REG_3 = dbug_reg_3_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[0*8+:8] = hl_weights_0_0_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[1*8+:8] = hl_weights_0_1_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[2*8+:8] = hl_weights_0_2_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[3*8+:8] = hl_weights_0_3_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[4*8+:8] = hl_weights_0_4_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[5*8+:8] = hl_weights_0_5_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[6*8+:8] = hl_weights_0_6_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[7*8+:8] = hl_weights_0_7_value_out;
    assign HWIF_OUT_HL_WEIGHTS_0[8*8+:8] = hl_weights_0_8_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[0*8+:8] = hl_weights_1_0_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[1*8+:8] = hl_weights_1_1_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[2*8+:8] = hl_weights_1_2_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[3*8+:8] = hl_weights_1_3_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[4*8+:8] = hl_weights_1_4_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[5*8+:8] = hl_weights_1_5_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[6*8+:8] = hl_weights_1_6_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[7*8+:8] = hl_weights_1_7_value_out;
    assign HWIF_OUT_HL_WEIGHTS_1[8*8+:8] = hl_weights_1_8_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[0*8+:8] = hl_weights_2_0_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[1*8+:8] = hl_weights_2_1_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[2*8+:8] = hl_weights_2_2_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[3*8+:8] = hl_weights_2_3_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[4*8+:8] = hl_weights_2_4_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[5*8+:8] = hl_weights_2_5_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[6*8+:8] = hl_weights_2_6_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[7*8+:8] = hl_weights_2_7_value_out;
    assign HWIF_OUT_HL_WEIGHTS_2[8*8+:8] = hl_weights_2_8_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[0*8+:8] = hl_weights_3_0_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[1*8+:8] = hl_weights_3_1_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[2*8+:8] = hl_weights_3_2_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[3*8+:8] = hl_weights_3_3_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[4*8+:8] = hl_weights_3_4_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[5*8+:8] = hl_weights_3_5_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[6*8+:8] = hl_weights_3_6_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[7*8+:8] = hl_weights_3_7_value_out;
    assign HWIF_OUT_HL_WEIGHTS_3[8*8+:8] = hl_weights_3_8_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[0*8+:8] = hl_weights_4_0_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[1*8+:8] = hl_weights_4_1_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[2*8+:8] = hl_weights_4_2_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[3*8+:8] = hl_weights_4_3_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[4*8+:8] = hl_weights_4_4_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[5*8+:8] = hl_weights_4_5_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[6*8+:8] = hl_weights_4_6_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[7*8+:8] = hl_weights_4_7_value_out;
    assign HWIF_OUT_HL_WEIGHTS_4[8*8+:8] = hl_weights_4_8_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[0*8+:8] = hl_weights_5_0_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[1*8+:8] = hl_weights_5_1_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[2*8+:8] = hl_weights_5_2_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[3*8+:8] = hl_weights_5_3_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[4*8+:8] = hl_weights_5_4_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[5*8+:8] = hl_weights_5_5_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[6*8+:8] = hl_weights_5_6_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[7*8+:8] = hl_weights_5_7_value_out;
    assign HWIF_OUT_HL_WEIGHTS_5[8*8+:8] = hl_weights_5_8_value_out;
    assign HWIF_OUT_HL_BIAS_0 = hl_bias_0_value_out;
    assign HWIF_OUT_HL_BIAS_1 = hl_bias_1_value_out;
    assign HWIF_OUT_HL_BIAS_2 = hl_bias_2_value_out;
    assign HWIF_OUT_HL_BIAS_3 = hl_bias_3_value_out;
    assign HWIF_OUT_HL_BIAS_4 = hl_bias_4_value_out;
    assign HWIF_OUT_HL_BIAS_5 = hl_bias_5_value_out;
    assign HWIF_OUT_OL_WEIGHTS_0[0*8+:8] = ol_weights_0_0_value_out;
    assign HWIF_OUT_OL_WEIGHTS_0[1*8+:8] = ol_weights_0_1_value_out;
    assign HWIF_OUT_OL_WEIGHTS_0[2*8+:8] = ol_weights_0_2_value_out;
    assign HWIF_OUT_OL_WEIGHTS_0[3*8+:8] = ol_weights_0_3_value_out;
    assign HWIF_OUT_OL_WEIGHTS_0[4*8+:8] = ol_weights_0_4_value_out;
    assign HWIF_OUT_OL_WEIGHTS_0[5*8+:8] = ol_weights_0_5_value_out;
    assign HWIF_OUT_OL_WEIGHTS_1[0*8+:8] = ol_weights_1_0_value_out;
    assign HWIF_OUT_OL_WEIGHTS_1[1*8+:8] = ol_weights_1_1_value_out;
    assign HWIF_OUT_OL_WEIGHTS_1[2*8+:8] = ol_weights_1_2_value_out;
    assign HWIF_OUT_OL_WEIGHTS_1[3*8+:8] = ol_weights_1_3_value_out;
    assign HWIF_OUT_OL_WEIGHTS_1[4*8+:8] = ol_weights_1_4_value_out;
    assign HWIF_OUT_OL_WEIGHTS_1[5*8+:8] = ol_weights_1_5_value_out;
    assign HWIF_OUT_OL_WEIGHTS_2[0*8+:8] = ol_weights_2_0_value_out;
    assign HWIF_OUT_OL_WEIGHTS_2[1*8+:8] = ol_weights_2_1_value_out;
    assign HWIF_OUT_OL_WEIGHTS_2[2*8+:8] = ol_weights_2_2_value_out;
    assign HWIF_OUT_OL_WEIGHTS_2[3*8+:8] = ol_weights_2_3_value_out;
    assign HWIF_OUT_OL_WEIGHTS_2[4*8+:8] = ol_weights_2_4_value_out;
    assign HWIF_OUT_OL_WEIGHTS_2[5*8+:8] = ol_weights_2_5_value_out;
    assign HWIF_OUT_OL_BIAS_0 = ol_bias_0_value_out;
    assign HWIF_OUT_OL_BIAS_1 = ol_bias_1_value_out;
    assign HWIF_OUT_OL_BIAS_2 = ol_bias_2_value_out;
    assign HWIF_OUT_INPUT_GRID_0 = input_grid_0_value_out;
    assign HWIF_OUT_INPUT_GRID_1 = input_grid_1_value_out;
    assign HWIF_OUT_INPUT_GRID_2 = input_grid_2_value_out;
    assign HWIF_OUT_INPUT_GRID_3 = input_grid_3_value_out;
    assign HWIF_OUT_INPUT_GRID_4 = input_grid_4_value_out;
    assign HWIF_OUT_INPUT_GRID_5 = input_grid_5_value_out;
    assign HWIF_OUT_INPUT_GRID_6 = input_grid_6_value_out;
    assign HWIF_OUT_INPUT_GRID_7 = input_grid_7_value_out;
    assign HWIF_OUT_INPUT_GRID_8 = input_grid_8_value_out;
    assign output_solution_0_value_in = HWIF_IN_OUTPUT_SOLUTION_0;
    assign output_solution_1_value_in = HWIF_IN_OUTPUT_SOLUTION_1;
    assign output_solution_2_value_in = HWIF_IN_OUTPUT_SOLUTION_2;
    assign HWIF_OUT_CORE_CTRL = core_ctrl_value_out;
    assign HWIF_OUT_CORE_DEBUG_INFO = core_debug_info_value_out;
    assign core_status_value_in = HWIF_IN_CORE_STATUS;
    assign HWIF_OUT_SEVENSEG_0 = sevenseg_0_value_out;
    assign HWIF_OUT_SEVENSEG_1 = sevenseg_1_value_out;
    assign HWIF_OUT_SEVENSEG_2 = sevenseg_2_value_out;
    assign HWIF_OUT_SEVENSEG_3 = sevenseg_3_value_out;
endmodule

`default_nettype wire