// Generated by  grogu  starting from JINJA templated  package_template.sv  file

`timescale 1ns/100ps

package cortez_regpool_pkg;
    typedef struct {
        logic [31:0] next;
    } SREG_GP__data__in_t;

    typedef struct {
        SREG_GP__data__in_t data;
    } __SREG_GP_desc_5ef8e987__in_t;

    typedef struct {
        SREG_GP__data__in_t data;
    } __SREG_GP_desc_192cf40b__in_t;

    typedef struct {
        SREG_GP__data__in_t data;
    } __SREG_GP_desc_3914c971__in_t;

    typedef struct {
        SREG_GP__data__in_t data;
    } __SREG_GP_desc_f81b7a58__in_t;

    typedef struct {
        SREG_GP__data__in_t data;
    } __SREG_GP_desc_a9321ecf__in_t;

    typedef struct {
        logic next;
    } SREG_CORE_STATUS__VALID_OUT__in_t;

    typedef struct {
        logic [30:0] next;
    } SREG_CORE_STATUS__reserved__in_t;

    typedef struct {
        SREG_CORE_STATUS__VALID_OUT__in_t VALID_OUT;
        SREG_CORE_STATUS__reserved__in_t reserved;
    } __SREG_CORE_STATUS__in_t;

    typedef struct {
        __SREG_GP_desc_5ef8e987__in_t OUTPUT_SOLUTION_0;
        __SREG_GP_desc_192cf40b__in_t OUTPUT_SOLUTION_1;
        __SREG_GP_desc_3914c971__in_t OUTPUT_SOLUTION_2;
        __SREG_GP_desc_f81b7a58__in_t OUTPUT_SOLUTION_3;
        __SREG_GP_desc_a9321ecf__in_t OUTPUT_SOLUTION_4;
        __SREG_CORE_STATUS__in_t CORE_STATUS;
    } regpool__in_t;

    typedef struct {
        logic [31:0] value;
    } CREG_GP__data__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_87e06ffa__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_71112b11__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_3b47a2db__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_17389f4c__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_c633792d__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_276409e4__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_eaf2e40b__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_81950287__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_38e26033__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_4840198e__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_76b51155__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_42f3f74b__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_ef319b76__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_d000765f__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_119a1e64__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_4393adc8__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_ab9cf01d__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_4aacfa7f__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_eb9aeae0__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_cbfca9c1__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_89fd8d94__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_ecdbd051__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_ddf7a8f1__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_133c6e30__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_3ca28a59__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_983c07a5__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_c0f894b3__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_4ad973d3__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_7f07ece3__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_722fe55a__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_60f4f964__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_45d123d1__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_094f4997__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_9ed6ad8b__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_78777a41__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_73c2f700__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_29ebafa0__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_7c5f45cb__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_51161f67__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_46e5fae0__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_4c0863de__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_73ca75ee__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_485f92ad__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_d933a9df__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_830ba7a4__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_3cacd53b__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_4651bdda__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_8f9a58b8__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_138ba6d8__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_2a3db292__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_57729190__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_7a0b89fc__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_16413858__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_5e3d25d5__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_48edd36b__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_c8ab3483__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_c118bc94__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_04a2222d__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_93020994__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_ff271a10__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_0cc54e2e__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_2640ef38__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_9298fc60__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_5894a249__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_15296df3__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_20cae9fd__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_36fff670__out_t;

    typedef struct {
        logic [31:0] value;
    } SREG_GP__data__out_t;

    typedef struct {
        SREG_GP__data__out_t data;
    } __SREG_GP_desc_5ef8e987__out_t;

    typedef struct {
        SREG_GP__data__out_t data;
    } __SREG_GP_desc_192cf40b__out_t;

    typedef struct {
        SREG_GP__data__out_t data;
    } __SREG_GP_desc_3914c971__out_t;

    typedef struct {
        SREG_GP__data__out_t data;
    } __SREG_GP_desc_f81b7a58__out_t;

    typedef struct {
        SREG_GP__data__out_t data;
    } __SREG_GP_desc_a9321ecf__out_t;

    typedef struct {
        logic value;
    } CREG_CORE_CTRL__RESET__out_t;

    typedef struct {
        logic value;
    } CREG_CORE_CTRL__LOAD_IN__out_t;

    typedef struct {
        logic [29:0] value;
    } CREG_CORE_CTRL__reserved__out_t;

    typedef struct {
        CREG_CORE_CTRL__RESET__out_t RESET;
        CREG_CORE_CTRL__LOAD_IN__out_t LOAD_IN;
        CREG_CORE_CTRL__reserved__out_t reserved;
    } __CREG_CORE_CTRL__out_t;

    typedef struct {
        logic value;
    } SREG_CORE_STATUS__VALID_OUT__out_t;

    typedef struct {
        logic [30:0] value;
    } SREG_CORE_STATUS__reserved__out_t;

    typedef struct {
        SREG_CORE_STATUS__VALID_OUT__out_t VALID_OUT;
        SREG_CORE_STATUS__reserved__out_t reserved;
    } __SREG_CORE_STATUS__out_t;

    typedef struct {
        __CREG_GP_desc_87e06ffa__out_t HL_WEIGHTS_0[25];
        __CREG_GP_desc_71112b11__out_t HL_WEIGHTS_1[25];
        __CREG_GP_desc_3b47a2db__out_t HL_WEIGHTS_2[25];
        __CREG_GP_desc_17389f4c__out_t HL_WEIGHTS_3[25];
        __CREG_GP_desc_c633792d__out_t HL_WEIGHTS_4[25];
        __CREG_GP_desc_276409e4__out_t HL_WEIGHTS_5[25];
        __CREG_GP_desc_eaf2e40b__out_t HL_WEIGHTS_6[25];
        __CREG_GP_desc_81950287__out_t HL_WEIGHTS_7[25];
        __CREG_GP_desc_38e26033__out_t HL_WEIGHTS_8[25];
        __CREG_GP_desc_4840198e__out_t HL_WEIGHTS_9[25];
        __CREG_GP_desc_76b51155__out_t HL_WEIGHTS_10[25];
        __CREG_GP_desc_42f3f74b__out_t HL_WEIGHTS_11[25];
        __CREG_GP_desc_ef319b76__out_t HL_WEIGHTS_12[25];
        __CREG_GP_desc_d000765f__out_t HL_WEIGHTS_13[25];
        __CREG_GP_desc_119a1e64__out_t HL_WEIGHTS_14[25];
        __CREG_GP_desc_4393adc8__out_t HL_WEIGHTS_15[25];
        __CREG_GP_desc_ab9cf01d__out_t HL_BIAS_0;
        __CREG_GP_desc_4aacfa7f__out_t HL_BIAS_1;
        __CREG_GP_desc_eb9aeae0__out_t HL_BIAS_2;
        __CREG_GP_desc_cbfca9c1__out_t HL_BIAS_3;
        __CREG_GP_desc_89fd8d94__out_t HL_BIAS_4;
        __CREG_GP_desc_ecdbd051__out_t HL_BIAS_5;
        __CREG_GP_desc_ddf7a8f1__out_t HL_BIAS_6;
        __CREG_GP_desc_133c6e30__out_t HL_BIAS_7;
        __CREG_GP_desc_3ca28a59__out_t HL_BIAS_8;
        __CREG_GP_desc_983c07a5__out_t HL_BIAS_9;
        __CREG_GP_desc_c0f894b3__out_t HL_BIAS_10;
        __CREG_GP_desc_4ad973d3__out_t HL_BIAS_11;
        __CREG_GP_desc_7f07ece3__out_t HL_BIAS_12;
        __CREG_GP_desc_722fe55a__out_t HL_BIAS_13;
        __CREG_GP_desc_60f4f964__out_t HL_BIAS_14;
        __CREG_GP_desc_45d123d1__out_t HL_BIAS_15;
        __CREG_GP_desc_094f4997__out_t OL_WEIGHTS_0[16];
        __CREG_GP_desc_9ed6ad8b__out_t OL_WEIGHTS_1[16];
        __CREG_GP_desc_78777a41__out_t OL_WEIGHTS_2[16];
        __CREG_GP_desc_73c2f700__out_t OL_WEIGHTS_3[16];
        __CREG_GP_desc_29ebafa0__out_t OL_WEIGHTS_4[16];
        __CREG_GP_desc_7c5f45cb__out_t OL_BIAS_0;
        __CREG_GP_desc_51161f67__out_t OL_BIAS_1;
        __CREG_GP_desc_46e5fae0__out_t OL_BIAS_2;
        __CREG_GP_desc_4c0863de__out_t OL_BIAS_3;
        __CREG_GP_desc_73ca75ee__out_t OL_BIAS_4;
        __CREG_GP_desc_485f92ad__out_t INPUT_GRID_0;
        __CREG_GP_desc_d933a9df__out_t INPUT_GRID_1;
        __CREG_GP_desc_830ba7a4__out_t INPUT_GRID_2;
        __CREG_GP_desc_3cacd53b__out_t INPUT_GRID_3;
        __CREG_GP_desc_4651bdda__out_t INPUT_GRID_4;
        __CREG_GP_desc_8f9a58b8__out_t INPUT_GRID_5;
        __CREG_GP_desc_138ba6d8__out_t INPUT_GRID_6;
        __CREG_GP_desc_2a3db292__out_t INPUT_GRID_7;
        __CREG_GP_desc_57729190__out_t INPUT_GRID_8;
        __CREG_GP_desc_7a0b89fc__out_t INPUT_GRID_9;
        __CREG_GP_desc_16413858__out_t INPUT_GRID_10;
        __CREG_GP_desc_5e3d25d5__out_t INPUT_GRID_11;
        __CREG_GP_desc_48edd36b__out_t INPUT_GRID_12;
        __CREG_GP_desc_c8ab3483__out_t INPUT_GRID_13;
        __CREG_GP_desc_c118bc94__out_t INPUT_GRID_14;
        __CREG_GP_desc_04a2222d__out_t INPUT_GRID_15;
        __CREG_GP_desc_93020994__out_t INPUT_GRID_16;
        __CREG_GP_desc_ff271a10__out_t INPUT_GRID_17;
        __CREG_GP_desc_0cc54e2e__out_t INPUT_GRID_18;
        __CREG_GP_desc_2640ef38__out_t INPUT_GRID_19;
        __CREG_GP_desc_9298fc60__out_t INPUT_GRID_20;
        __CREG_GP_desc_5894a249__out_t INPUT_GRID_21;
        __CREG_GP_desc_15296df3__out_t INPUT_GRID_22;
        __CREG_GP_desc_20cae9fd__out_t INPUT_GRID_23;
        __CREG_GP_desc_36fff670__out_t INPUT_GRID_24;
        __SREG_GP_desc_5ef8e987__out_t OUTPUT_SOLUTION_0;
        __SREG_GP_desc_192cf40b__out_t OUTPUT_SOLUTION_1;
        __SREG_GP_desc_3914c971__out_t OUTPUT_SOLUTION_2;
        __SREG_GP_desc_f81b7a58__out_t OUTPUT_SOLUTION_3;
        __SREG_GP_desc_a9321ecf__out_t OUTPUT_SOLUTION_4;
        __CREG_CORE_CTRL__out_t CORE_CTRL;
        __SREG_CORE_STATUS__out_t CORE_STATUS;
    } regpool__out_t;
endpackage