// Generated by  grogu  starting from JINJA templated  package_template.sv  file

`timescale 1ns/100ps

package cortez_regpool_pkg;
    typedef struct {
        logic [7:0] next;
    } SREG_GP__data__in_t;

    typedef struct {
        SREG_GP__data__in_t data;
    } __SREG_GP_desc_5ef8e987__in_t;

    typedef struct {
        SREG_GP__data__in_t data;
    } __SREG_GP_desc_192cf40b__in_t;

    typedef struct {
        SREG_GP__data__in_t data;
    } __SREG_GP_desc_3914c971__in_t;

    typedef struct {
        logic next;
    } SREG_CORE_STATUS__VALID_OUT__in_t;

    typedef struct {
        logic [6:0] next;
    } SREG_CORE_STATUS__reserved__in_t;

    typedef struct {
        SREG_CORE_STATUS__VALID_OUT__in_t VALID_OUT;
        SREG_CORE_STATUS__reserved__in_t reserved;
    } __SREG_CORE_STATUS__in_t;

    typedef struct {
        __SREG_GP_desc_5ef8e987__in_t OUTPUT_SOLUTION_0;
        __SREG_GP_desc_192cf40b__in_t OUTPUT_SOLUTION_1;
        __SREG_GP_desc_3914c971__in_t OUTPUT_SOLUTION_2;
        __SREG_CORE_STATUS__in_t CORE_STATUS;
    } regpool__in_t;

    typedef struct {
        logic [7:0] value;
    } CREG_GP__data__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_87e06ffa__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_71112b11__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_3b47a2db__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_17389f4c__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_c633792d__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_276409e4__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_ab9cf01d__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_4aacfa7f__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_eb9aeae0__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_cbfca9c1__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_89fd8d94__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_ecdbd051__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_094f4997__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_9ed6ad8b__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_78777a41__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_7c5f45cb__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_51161f67__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_46e5fae0__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_485f92ad__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_d933a9df__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_830ba7a4__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_3cacd53b__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_4651bdda__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_8f9a58b8__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_138ba6d8__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_2a3db292__out_t;

    typedef struct {
        CREG_GP__data__out_t data;
    } __CREG_GP_desc_57729190__out_t;

    typedef struct {
        logic [7:0] value;
    } SREG_GP__data__out_t;

    typedef struct {
        SREG_GP__data__out_t data;
    } __SREG_GP_desc_5ef8e987__out_t;

    typedef struct {
        SREG_GP__data__out_t data;
    } __SREG_GP_desc_192cf40b__out_t;

    typedef struct {
        SREG_GP__data__out_t data;
    } __SREG_GP_desc_3914c971__out_t;

    typedef struct {
        logic value;
    } CREG_CORE_CTRL__RESET__out_t;

    typedef struct {
        logic value;
    } CREG_CORE_CTRL__LOAD_IN__out_t;

    typedef struct {
        logic value;
    } CREG_CORE_CTRL__CFG_DONE__out_t;

    typedef struct {
        logic [4:0] value;
    } CREG_CORE_CTRL__reserved__out_t;

    typedef struct {
        CREG_CORE_CTRL__RESET__out_t RESET;
        CREG_CORE_CTRL__LOAD_IN__out_t LOAD_IN;
        CREG_CORE_CTRL__CFG_DONE__out_t CFG_DONE;
        CREG_CORE_CTRL__reserved__out_t reserved;
    } __CREG_CORE_CTRL__out_t;

    typedef struct {
        logic value;
    } SREG_CORE_STATUS__VALID_OUT__out_t;

    typedef struct {
        logic [6:0] value;
    } SREG_CORE_STATUS__reserved__out_t;

    typedef struct {
        SREG_CORE_STATUS__VALID_OUT__out_t VALID_OUT;
        SREG_CORE_STATUS__reserved__out_t reserved;
    } __SREG_CORE_STATUS__out_t;

    typedef struct {
        __CREG_GP_desc_87e06ffa__out_t HL_WEIGHTS_0[9];
        __CREG_GP_desc_71112b11__out_t HL_WEIGHTS_1[9];
        __CREG_GP_desc_3b47a2db__out_t HL_WEIGHTS_2[9];
        __CREG_GP_desc_17389f4c__out_t HL_WEIGHTS_3[9];
        __CREG_GP_desc_c633792d__out_t HL_WEIGHTS_4[9];
        __CREG_GP_desc_276409e4__out_t HL_WEIGHTS_5[9];
        __CREG_GP_desc_ab9cf01d__out_t HL_BIAS_0;
        __CREG_GP_desc_4aacfa7f__out_t HL_BIAS_1;
        __CREG_GP_desc_eb9aeae0__out_t HL_BIAS_2;
        __CREG_GP_desc_cbfca9c1__out_t HL_BIAS_3;
        __CREG_GP_desc_89fd8d94__out_t HL_BIAS_4;
        __CREG_GP_desc_ecdbd051__out_t HL_BIAS_5;
        __CREG_GP_desc_094f4997__out_t OL_WEIGHTS_0[6];
        __CREG_GP_desc_9ed6ad8b__out_t OL_WEIGHTS_1[6];
        __CREG_GP_desc_78777a41__out_t OL_WEIGHTS_2[6];
        __CREG_GP_desc_7c5f45cb__out_t OL_BIAS_0;
        __CREG_GP_desc_51161f67__out_t OL_BIAS_1;
        __CREG_GP_desc_46e5fae0__out_t OL_BIAS_2;
        __CREG_GP_desc_485f92ad__out_t INPUT_GRID_0;
        __CREG_GP_desc_d933a9df__out_t INPUT_GRID_1;
        __CREG_GP_desc_830ba7a4__out_t INPUT_GRID_2;
        __CREG_GP_desc_3cacd53b__out_t INPUT_GRID_3;
        __CREG_GP_desc_4651bdda__out_t INPUT_GRID_4;
        __CREG_GP_desc_8f9a58b8__out_t INPUT_GRID_5;
        __CREG_GP_desc_138ba6d8__out_t INPUT_GRID_6;
        __CREG_GP_desc_2a3db292__out_t INPUT_GRID_7;
        __CREG_GP_desc_57729190__out_t INPUT_GRID_8;
        __SREG_GP_desc_5ef8e987__out_t OUTPUT_SOLUTION_0;
        __SREG_GP_desc_192cf40b__out_t OUTPUT_SOLUTION_1;
        __SREG_GP_desc_3914c971__out_t OUTPUT_SOLUTION_2;
        __CREG_CORE_CTRL__out_t CORE_CTRL;
        __SREG_CORE_STATUS__out_t CORE_STATUS;
    } regpool__out_t;
endpackage