// Generated by  grogu  starting from JINJA templated  reg_defines.h  file

#pragma once

// Array registers are defined only once

// ol_neuron_regfile_WEIGHT_0 @+0x0
typedef union ol_neuron_regfile_WEIGHT_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_WEIGHT_0_reg_t;

// ol_neuron_regfile_WEIGHT_1 @+0x1
typedef union ol_neuron_regfile_WEIGHT_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_WEIGHT_1_reg_t;

// ol_neuron_regfile_WEIGHT_2 @+0x2
typedef union ol_neuron_regfile_WEIGHT_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_WEIGHT_2_reg_t;

// ol_neuron_regfile_WEIGHT_3 @+0x3
typedef union ol_neuron_regfile_WEIGHT_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_WEIGHT_3_reg_t;

// ol_neuron_regfile_WEIGHT_4 @+0x4
typedef union ol_neuron_regfile_WEIGHT_4_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_WEIGHT_4_reg_t;

// ol_neuron_regfile_WEIGHT_5 @+0x5
typedef union ol_neuron_regfile_WEIGHT_5_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_WEIGHT_5_reg_t;

// ol_neuron_regfile_WEIGHT_6 @+0x6
typedef union ol_neuron_regfile_WEIGHT_6_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_WEIGHT_6_reg_t;

// ol_neuron_regfile_WEIGHT_7 @+0x7
typedef union ol_neuron_regfile_WEIGHT_7_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_WEIGHT_7_reg_t;

// ol_neuron_regfile_BIAS @+0x8
typedef union ol_neuron_regfile_BIAS_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} ol_neuron_regfile_BIAS_reg_t;
