// Generated by  grogu  starting from JINJA templated  offset_defines.h  file

#pragma once

// Write-only registers

// Read-only registers

// Read/Write registers
#define OL_NEURON_REGFILE_WEIGHT_0_OFFSET 0x0
#define OL_NEURON_REGFILE_WEIGHT_1_OFFSET 0x1
#define OL_NEURON_REGFILE_WEIGHT_2_OFFSET 0x2
#define OL_NEURON_REGFILE_WEIGHT_3_OFFSET 0x3
#define OL_NEURON_REGFILE_WEIGHT_4_OFFSET 0x4
#define OL_NEURON_REGFILE_WEIGHT_5_OFFSET 0x5
#define OL_NEURON_REGFILE_WEIGHT_6_OFFSET 0x6
#define OL_NEURON_REGFILE_WEIGHT_7_OFFSET 0x7
#define OL_NEURON_REGFILE_BIAS_OFFSET 0x8