# COCOTB configuration
TOPLEVEL_LANG = verilog
SIM ?= verilator

# Prefix for change of hierarchy. Do *not* modify this line!
VERILOG_SOURCES = $(shell grep -E "\.[s]*v$$" ../../rtl/rtl_sources.list | sed 's/^/\.\.\/\.\.\/rtl\//g' )

# Include dirs
VERILOG_INCLUDE_DIRS=../../rtl -I../../grogu ../../grogu/grogu.gen/CORE_REGFILE/rtl ../../grogu/grogu.gen/HL_NEURON_REGFILE/rtl ../../grogu/grogu.gen/OL_NEURON_REGFILE/rtl

# Top-level module determines also test name
TOPLEVEL ?= FIXED_POINT_ACT_FUN
MODULE ?= test_$(shell echo $(TOPLEVEL) | tr 'A-Z' 'a-z')

# Miscellanea
RANDOM_SEED ?= $( date +%N )
SEED ?= $(RANDOM_SEED)
WAVES ?= 0

# Disable warnings
override EXTRA_ARGS += -Wno-WIDTHEXPAND -Wno-WIDTHTRUNC -Wno-CASEINCOMPLETE

# Optional waveforms
ifeq ($(WAVES),1)
override EXTRA_ARGS += --trace-fst --trace-structs
endif

# Include COCOTB Makefiles
include $(shell cocotb-config --makefiles)/Makefile.sim

# User-defined clean all
purge: clean
	find . -name __pycache__ -exec rm -fR {} +

