// Generated by  grogu  starting from JINJA templated  reg_defines.h  file

#pragma once

// Array registers are defined only once

// core_regfile_DBUG_REG_0 @+0x0
typedef union core_regfile_DBUG_REG_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_DBUG_REG_0_reg_t;

// core_regfile_DBUG_REG_1 @+0x1
typedef union core_regfile_DBUG_REG_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_DBUG_REG_1_reg_t;

// core_regfile_DBUG_REG_2 @+0x2
typedef union core_regfile_DBUG_REG_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_DBUG_REG_2_reg_t;

// core_regfile_DBUG_REG_3 @+0x3
typedef union core_regfile_DBUG_REG_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_DBUG_REG_3_reg_t;

// core_regfile_INPUT_GRID_0 @+0x4
typedef union core_regfile_INPUT_GRID_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_0_reg_t;

// core_regfile_INPUT_GRID_1 @+0x5
typedef union core_regfile_INPUT_GRID_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_1_reg_t;

// core_regfile_INPUT_GRID_2 @+0x6
typedef union core_regfile_INPUT_GRID_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_2_reg_t;

// core_regfile_INPUT_GRID_3 @+0x7
typedef union core_regfile_INPUT_GRID_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_3_reg_t;

// core_regfile_INPUT_GRID_4 @+0x8
typedef union core_regfile_INPUT_GRID_4_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_4_reg_t;

// core_regfile_INPUT_GRID_5 @+0x9
typedef union core_regfile_INPUT_GRID_5_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_5_reg_t;

// core_regfile_INPUT_GRID_6 @+0xa
typedef union core_regfile_INPUT_GRID_6_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_6_reg_t;

// core_regfile_INPUT_GRID_7 @+0xb
typedef union core_regfile_INPUT_GRID_7_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_7_reg_t;

// core_regfile_INPUT_GRID_8 @+0xc
typedef union core_regfile_INPUT_GRID_8_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_8_reg_t;

// core_regfile_INPUT_GRID_9 @+0xd
typedef union core_regfile_INPUT_GRID_9_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_9_reg_t;

// core_regfile_INPUT_GRID_10 @+0xe
typedef union core_regfile_INPUT_GRID_10_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_10_reg_t;

// core_regfile_INPUT_GRID_11 @+0xf
typedef union core_regfile_INPUT_GRID_11_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_11_reg_t;

// core_regfile_INPUT_GRID_12 @+0x10
typedef union core_regfile_INPUT_GRID_12_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_12_reg_t;

// core_regfile_INPUT_GRID_13 @+0x11
typedef union core_regfile_INPUT_GRID_13_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_13_reg_t;

// core_regfile_INPUT_GRID_14 @+0x12
typedef union core_regfile_INPUT_GRID_14_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_14_reg_t;

// core_regfile_INPUT_GRID_15 @+0x13
typedef union core_regfile_INPUT_GRID_15_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_INPUT_GRID_15_reg_t;

// core_regfile_OUTPUT_SOLUTION_0 @+0x14
typedef union core_regfile_OUTPUT_SOLUTION_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_OUTPUT_SOLUTION_0_reg_t;

// core_regfile_OUTPUT_SOLUTION_1 @+0x15
typedef union core_regfile_OUTPUT_SOLUTION_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_OUTPUT_SOLUTION_1_reg_t;

// core_regfile_OUTPUT_SOLUTION_2 @+0x16
typedef union core_regfile_OUTPUT_SOLUTION_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_OUTPUT_SOLUTION_2_reg_t;

// core_regfile_OUTPUT_SOLUTION_3 @+0x17
typedef union core_regfile_OUTPUT_SOLUTION_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_OUTPUT_SOLUTION_3_reg_t;

// core_regfile_OUTPUT_SOLUTION_4 @+0x18
typedef union core_regfile_OUTPUT_SOLUTION_4_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_OUTPUT_SOLUTION_4_reg_t;

// core_regfile_CORE_CTRL @+0x19
typedef union core_regfile_CORE_CTRL_reg_tag {
    struct {
        uint32_t RESET : 1; // @[0:0]
        uint32_t LOAD_IN : 1; // @[1:1]
        uint32_t CFG_DONE : 1; // @[2:2]
        uint32_t reserved : 5; // @[7:3]
    } fields;
    uint32_t value;
} core_regfile_CORE_CTRL_reg_t;

// core_regfile_CORE_DEBUG_INFO @+0x1a
typedef union core_regfile_CORE_DEBUG_INFO_reg_tag {
    struct {
        uint32_t RESET_START : 1; // @[0:0]
        uint32_t RESET_END : 1; // @[1:1]
        uint32_t CONFIG_START : 1; // @[2:2]
        uint32_t CONFIG_END : 1; // @[3:3]
        uint32_t TEST_START : 1; // @[4:4]
        uint32_t TEST_END : 1; // @[5:5]
        uint32_t TEST_ERR : 1; // @[6:6]
        uint32_t reserved : 1; // @[7:7]
    } fields;
    uint32_t value;
} core_regfile_CORE_DEBUG_INFO_reg_t;

// core_regfile_CORE_STATUS @+0x1b
typedef union core_regfile_CORE_STATUS_reg_tag {
    struct {
        uint32_t VALID_OUT : 1; // @[0:0]
        uint32_t reserved : 7; // @[7:1]
    } fields;
    uint32_t value;
} core_regfile_CORE_STATUS_reg_t;

// core_regfile_SEVENSEG_0 @+0x1c
typedef union core_regfile_SEVENSEG_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_SEVENSEG_0_reg_t;

// core_regfile_SEVENSEG_1 @+0x1d
typedef union core_regfile_SEVENSEG_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_SEVENSEG_1_reg_t;

// core_regfile_SEVENSEG_2 @+0x1e
typedef union core_regfile_SEVENSEG_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_SEVENSEG_2_reg_t;

// core_regfile_SEVENSEG_3 @+0x1f
typedef union core_regfile_SEVENSEG_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} core_regfile_SEVENSEG_3_reg_t;
