# COCOTB configuration
TOPLEVEL_LANG = verilog
SIM ?= icarus

# Prefix for change of hierarchy. Do *not* modify this line!
VERILOG_SOURCES = $(shell grep -E "\.[s]*v$$" ../../rtl/rtl_sources.list | sed 's/^/\.\.\/\.\.\/rtl\//g' )

# Top-level module determines also test name
TOPLEVEL ?= FIXED_POINT_ACT_FUN
MODULE ?= test_$(shell echo $(TOPLEVEL) | tr 'A-Z' 'a-z')

# Miscellanea
RANDOM_SEED ?= $( date +%N )
SEED ?= $(RANDOM_SEED)

# Include options from file
override COMPILE_ARGS += -c cmdfile.icarus

# Include COCOTB Makefiles
include $(shell cocotb-config --makefiles)/Makefile.sim

# User-defined clean all
purge: clean
	find . -name __pycache__ -exec rm -fR {} +

