// Generated by  grogu  starting from JINJA templated  reg_defines.h  file

#pragma once

// Array registers are defined only once

// CORTEZ_HL_WEIGHTS_0[9] @+0x0:0x8
typedef union CORTEZ_HL_WEIGHTS_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_0_reg_t;

// CORTEZ_HL_WEIGHTS_1[9] @+0x9:0x11
typedef union CORTEZ_HL_WEIGHTS_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_1_reg_t;

// CORTEZ_HL_WEIGHTS_2[9] @+0x12:0x1a
typedef union CORTEZ_HL_WEIGHTS_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_2_reg_t;

// CORTEZ_HL_WEIGHTS_3[9] @+0x1b:0x23
typedef union CORTEZ_HL_WEIGHTS_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_3_reg_t;

// CORTEZ_HL_WEIGHTS_4[9] @+0x24:0x2c
typedef union CORTEZ_HL_WEIGHTS_4_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_4_reg_t;

// CORTEZ_HL_WEIGHTS_5[9] @+0x2d:0x35
typedef union CORTEZ_HL_WEIGHTS_5_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_5_reg_t;

// CORTEZ_HL_BIAS_0 @+0x36
typedef union CORTEZ_HL_BIAS_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_0_reg_t;

// CORTEZ_HL_BIAS_1 @+0x37
typedef union CORTEZ_HL_BIAS_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_1_reg_t;

// CORTEZ_HL_BIAS_2 @+0x38
typedef union CORTEZ_HL_BIAS_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_2_reg_t;

// CORTEZ_HL_BIAS_3 @+0x39
typedef union CORTEZ_HL_BIAS_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_3_reg_t;

// CORTEZ_HL_BIAS_4 @+0x3a
typedef union CORTEZ_HL_BIAS_4_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_4_reg_t;

// CORTEZ_HL_BIAS_5 @+0x3b
typedef union CORTEZ_HL_BIAS_5_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_5_reg_t;

// CORTEZ_OL_WEIGHTS_0[6] @+0x3c:0x41
typedef union CORTEZ_OL_WEIGHTS_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_WEIGHTS_0_reg_t;

// CORTEZ_OL_WEIGHTS_1[6] @+0x42:0x47
typedef union CORTEZ_OL_WEIGHTS_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_WEIGHTS_1_reg_t;

// CORTEZ_OL_WEIGHTS_2[6] @+0x48:0x4d
typedef union CORTEZ_OL_WEIGHTS_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_WEIGHTS_2_reg_t;

// CORTEZ_OL_BIAS_0 @+0x4e
typedef union CORTEZ_OL_BIAS_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_BIAS_0_reg_t;

// CORTEZ_OL_BIAS_1 @+0x4f
typedef union CORTEZ_OL_BIAS_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_BIAS_1_reg_t;

// CORTEZ_OL_BIAS_2 @+0x50
typedef union CORTEZ_OL_BIAS_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_BIAS_2_reg_t;

// CORTEZ_INPUT_GRID_0 @+0x51
typedef union CORTEZ_INPUT_GRID_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_0_reg_t;

// CORTEZ_INPUT_GRID_1 @+0x52
typedef union CORTEZ_INPUT_GRID_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_1_reg_t;

// CORTEZ_INPUT_GRID_2 @+0x53
typedef union CORTEZ_INPUT_GRID_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_2_reg_t;

// CORTEZ_INPUT_GRID_3 @+0x54
typedef union CORTEZ_INPUT_GRID_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_3_reg_t;

// CORTEZ_INPUT_GRID_4 @+0x55
typedef union CORTEZ_INPUT_GRID_4_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_4_reg_t;

// CORTEZ_INPUT_GRID_5 @+0x56
typedef union CORTEZ_INPUT_GRID_5_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_5_reg_t;

// CORTEZ_INPUT_GRID_6 @+0x57
typedef union CORTEZ_INPUT_GRID_6_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_6_reg_t;

// CORTEZ_INPUT_GRID_7 @+0x58
typedef union CORTEZ_INPUT_GRID_7_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_7_reg_t;

// CORTEZ_INPUT_GRID_8 @+0x59
typedef union CORTEZ_INPUT_GRID_8_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_8_reg_t;

// CORTEZ_OUTPUT_SOLUTION_0 @+0x5a
typedef union CORTEZ_OUTPUT_SOLUTION_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OUTPUT_SOLUTION_0_reg_t;

// CORTEZ_OUTPUT_SOLUTION_1 @+0x5b
typedef union CORTEZ_OUTPUT_SOLUTION_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OUTPUT_SOLUTION_1_reg_t;

// CORTEZ_OUTPUT_SOLUTION_2 @+0x5c
typedef union CORTEZ_OUTPUT_SOLUTION_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} CORTEZ_OUTPUT_SOLUTION_2_reg_t;

// CORTEZ_CORE_CTRL @+0x5d
typedef union CORTEZ_CORE_CTRL_reg_tag {
    struct {
        uint32_t RESET : 1; // @[0:0]
        uint32_t LOAD_IN : 1; // @[1:1]
        uint32_t CFG_DONE : 1; // @[2:2]
        uint32_t reserved : 5; // @[7:3]
    } fields;
    uint32_t value;
} CORTEZ_CORE_CTRL_reg_t;

// CORTEZ_CORE_STATUS @+0x5e
typedef union CORTEZ_CORE_STATUS_reg_tag {
    struct {
        uint32_t VALID_OUT : 1; // @[0:0]
        uint32_t reserved : 7; // @[7:1]
    } fields;
    uint32_t value;
} CORTEZ_CORE_STATUS_reg_t;
