// Generated by  grogu  starting from JINJA templated  reg_defines.h  file

#pragma once

// Array registers are defined only once

// CORTEZ_HL_WEIGHTS_0[25] @+0x0:0x60
typedef union CORTEZ_HL_WEIGHTS_0_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_0_reg_t;

// CORTEZ_HL_WEIGHTS_1[25] @+0x64:0xc4
typedef union CORTEZ_HL_WEIGHTS_1_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_1_reg_t;

// CORTEZ_HL_WEIGHTS_2[25] @+0xc8:0x128
typedef union CORTEZ_HL_WEIGHTS_2_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_2_reg_t;

// CORTEZ_HL_WEIGHTS_3[25] @+0x12c:0x18c
typedef union CORTEZ_HL_WEIGHTS_3_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_3_reg_t;

// CORTEZ_HL_WEIGHTS_4[25] @+0x190:0x1f0
typedef union CORTEZ_HL_WEIGHTS_4_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_4_reg_t;

// CORTEZ_HL_WEIGHTS_5[25] @+0x1f4:0x254
typedef union CORTEZ_HL_WEIGHTS_5_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_5_reg_t;

// CORTEZ_HL_WEIGHTS_6[25] @+0x258:0x2b8
typedef union CORTEZ_HL_WEIGHTS_6_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_6_reg_t;

// CORTEZ_HL_WEIGHTS_7[25] @+0x2bc:0x31c
typedef union CORTEZ_HL_WEIGHTS_7_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_7_reg_t;

// CORTEZ_HL_WEIGHTS_8[25] @+0x320:0x380
typedef union CORTEZ_HL_WEIGHTS_8_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_8_reg_t;

// CORTEZ_HL_WEIGHTS_9[25] @+0x384:0x3e4
typedef union CORTEZ_HL_WEIGHTS_9_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_9_reg_t;

// CORTEZ_HL_WEIGHTS_10[25] @+0x3e8:0x448
typedef union CORTEZ_HL_WEIGHTS_10_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_10_reg_t;

// CORTEZ_HL_WEIGHTS_11[25] @+0x44c:0x4ac
typedef union CORTEZ_HL_WEIGHTS_11_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_11_reg_t;

// CORTEZ_HL_WEIGHTS_12[25] @+0x4b0:0x510
typedef union CORTEZ_HL_WEIGHTS_12_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_12_reg_t;

// CORTEZ_HL_WEIGHTS_13[25] @+0x514:0x574
typedef union CORTEZ_HL_WEIGHTS_13_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_13_reg_t;

// CORTEZ_HL_WEIGHTS_14[25] @+0x578:0x5d8
typedef union CORTEZ_HL_WEIGHTS_14_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_14_reg_t;

// CORTEZ_HL_WEIGHTS_15[25] @+0x5dc:0x63c
typedef union CORTEZ_HL_WEIGHTS_15_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_WEIGHTS_15_reg_t;

// CORTEZ_HL_BIAS_0 @+0x640
typedef union CORTEZ_HL_BIAS_0_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_0_reg_t;

// CORTEZ_HL_BIAS_1 @+0x644
typedef union CORTEZ_HL_BIAS_1_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_1_reg_t;

// CORTEZ_HL_BIAS_2 @+0x648
typedef union CORTEZ_HL_BIAS_2_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_2_reg_t;

// CORTEZ_HL_BIAS_3 @+0x64c
typedef union CORTEZ_HL_BIAS_3_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_3_reg_t;

// CORTEZ_HL_BIAS_4 @+0x650
typedef union CORTEZ_HL_BIAS_4_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_4_reg_t;

// CORTEZ_HL_BIAS_5 @+0x654
typedef union CORTEZ_HL_BIAS_5_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_5_reg_t;

// CORTEZ_HL_BIAS_6 @+0x658
typedef union CORTEZ_HL_BIAS_6_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_6_reg_t;

// CORTEZ_HL_BIAS_7 @+0x65c
typedef union CORTEZ_HL_BIAS_7_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_7_reg_t;

// CORTEZ_HL_BIAS_8 @+0x660
typedef union CORTEZ_HL_BIAS_8_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_8_reg_t;

// CORTEZ_HL_BIAS_9 @+0x664
typedef union CORTEZ_HL_BIAS_9_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_9_reg_t;

// CORTEZ_HL_BIAS_10 @+0x668
typedef union CORTEZ_HL_BIAS_10_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_10_reg_t;

// CORTEZ_HL_BIAS_11 @+0x66c
typedef union CORTEZ_HL_BIAS_11_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_11_reg_t;

// CORTEZ_HL_BIAS_12 @+0x670
typedef union CORTEZ_HL_BIAS_12_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_12_reg_t;

// CORTEZ_HL_BIAS_13 @+0x674
typedef union CORTEZ_HL_BIAS_13_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_13_reg_t;

// CORTEZ_HL_BIAS_14 @+0x678
typedef union CORTEZ_HL_BIAS_14_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_14_reg_t;

// CORTEZ_HL_BIAS_15 @+0x67c
typedef union CORTEZ_HL_BIAS_15_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_HL_BIAS_15_reg_t;

// CORTEZ_OL_WEIGHTS_0[16] @+0x680:0x6bc
typedef union CORTEZ_OL_WEIGHTS_0_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_WEIGHTS_0_reg_t;

// CORTEZ_OL_WEIGHTS_1[16] @+0x6c0:0x6fc
typedef union CORTEZ_OL_WEIGHTS_1_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_WEIGHTS_1_reg_t;

// CORTEZ_OL_WEIGHTS_2[16] @+0x700:0x73c
typedef union CORTEZ_OL_WEIGHTS_2_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_WEIGHTS_2_reg_t;

// CORTEZ_OL_WEIGHTS_3[16] @+0x740:0x77c
typedef union CORTEZ_OL_WEIGHTS_3_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_WEIGHTS_3_reg_t;

// CORTEZ_OL_WEIGHTS_4[16] @+0x780:0x7bc
typedef union CORTEZ_OL_WEIGHTS_4_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_WEIGHTS_4_reg_t;

// CORTEZ_OL_BIAS_0 @+0x7c0
typedef union CORTEZ_OL_BIAS_0_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_BIAS_0_reg_t;

// CORTEZ_OL_BIAS_1 @+0x7c4
typedef union CORTEZ_OL_BIAS_1_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_BIAS_1_reg_t;

// CORTEZ_OL_BIAS_2 @+0x7c8
typedef union CORTEZ_OL_BIAS_2_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_BIAS_2_reg_t;

// CORTEZ_OL_BIAS_3 @+0x7cc
typedef union CORTEZ_OL_BIAS_3_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_BIAS_3_reg_t;

// CORTEZ_OL_BIAS_4 @+0x7d0
typedef union CORTEZ_OL_BIAS_4_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OL_BIAS_4_reg_t;

// CORTEZ_INPUT_GRID_0 @+0x7d4
typedef union CORTEZ_INPUT_GRID_0_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_0_reg_t;

// CORTEZ_INPUT_GRID_1 @+0x7d8
typedef union CORTEZ_INPUT_GRID_1_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_1_reg_t;

// CORTEZ_INPUT_GRID_2 @+0x7dc
typedef union CORTEZ_INPUT_GRID_2_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_2_reg_t;

// CORTEZ_INPUT_GRID_3 @+0x7e0
typedef union CORTEZ_INPUT_GRID_3_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_3_reg_t;

// CORTEZ_INPUT_GRID_4 @+0x7e4
typedef union CORTEZ_INPUT_GRID_4_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_4_reg_t;

// CORTEZ_INPUT_GRID_5 @+0x7e8
typedef union CORTEZ_INPUT_GRID_5_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_5_reg_t;

// CORTEZ_INPUT_GRID_6 @+0x7ec
typedef union CORTEZ_INPUT_GRID_6_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_6_reg_t;

// CORTEZ_INPUT_GRID_7 @+0x7f0
typedef union CORTEZ_INPUT_GRID_7_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_7_reg_t;

// CORTEZ_INPUT_GRID_8 @+0x7f4
typedef union CORTEZ_INPUT_GRID_8_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_8_reg_t;

// CORTEZ_INPUT_GRID_9 @+0x7f8
typedef union CORTEZ_INPUT_GRID_9_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_9_reg_t;

// CORTEZ_INPUT_GRID_10 @+0x7fc
typedef union CORTEZ_INPUT_GRID_10_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_10_reg_t;

// CORTEZ_INPUT_GRID_11 @+0x800
typedef union CORTEZ_INPUT_GRID_11_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_11_reg_t;

// CORTEZ_INPUT_GRID_12 @+0x804
typedef union CORTEZ_INPUT_GRID_12_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_12_reg_t;

// CORTEZ_INPUT_GRID_13 @+0x808
typedef union CORTEZ_INPUT_GRID_13_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_13_reg_t;

// CORTEZ_INPUT_GRID_14 @+0x80c
typedef union CORTEZ_INPUT_GRID_14_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_14_reg_t;

// CORTEZ_INPUT_GRID_15 @+0x810
typedef union CORTEZ_INPUT_GRID_15_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_15_reg_t;

// CORTEZ_INPUT_GRID_16 @+0x814
typedef union CORTEZ_INPUT_GRID_16_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_16_reg_t;

// CORTEZ_INPUT_GRID_17 @+0x818
typedef union CORTEZ_INPUT_GRID_17_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_17_reg_t;

// CORTEZ_INPUT_GRID_18 @+0x81c
typedef union CORTEZ_INPUT_GRID_18_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_18_reg_t;

// CORTEZ_INPUT_GRID_19 @+0x820
typedef union CORTEZ_INPUT_GRID_19_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_19_reg_t;

// CORTEZ_INPUT_GRID_20 @+0x824
typedef union CORTEZ_INPUT_GRID_20_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_20_reg_t;

// CORTEZ_INPUT_GRID_21 @+0x828
typedef union CORTEZ_INPUT_GRID_21_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_21_reg_t;

// CORTEZ_INPUT_GRID_22 @+0x82c
typedef union CORTEZ_INPUT_GRID_22_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_22_reg_t;

// CORTEZ_INPUT_GRID_23 @+0x830
typedef union CORTEZ_INPUT_GRID_23_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_23_reg_t;

// CORTEZ_INPUT_GRID_24 @+0x834
typedef union CORTEZ_INPUT_GRID_24_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_INPUT_GRID_24_reg_t;

// CORTEZ_OUTPUT_SOLUTION_0 @+0x838
typedef union CORTEZ_OUTPUT_SOLUTION_0_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OUTPUT_SOLUTION_0_reg_t;

// CORTEZ_OUTPUT_SOLUTION_1 @+0x83c
typedef union CORTEZ_OUTPUT_SOLUTION_1_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OUTPUT_SOLUTION_1_reg_t;

// CORTEZ_OUTPUT_SOLUTION_2 @+0x840
typedef union CORTEZ_OUTPUT_SOLUTION_2_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OUTPUT_SOLUTION_2_reg_t;

// CORTEZ_OUTPUT_SOLUTION_3 @+0x844
typedef union CORTEZ_OUTPUT_SOLUTION_3_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OUTPUT_SOLUTION_3_reg_t;

// CORTEZ_OUTPUT_SOLUTION_4 @+0x848
typedef union CORTEZ_OUTPUT_SOLUTION_4_reg_tag {
    struct {
        uint32_t data : 32; // @[31:0]
    } fields;
    uint32_t value;
} CORTEZ_OUTPUT_SOLUTION_4_reg_t;

// CORTEZ_CORE_CTRL @+0x84c
typedef union CORTEZ_CORE_CTRL_reg_tag {
    struct {
        uint32_t RESET : 1; // @[0:0]
        uint32_t LOAD_IN : 1; // @[1:1]
        uint32_t reserved : 30; // @[31:2]
    } fields;
    uint32_t value;
} CORTEZ_CORE_CTRL_reg_t;

// CORTEZ_CORE_STATUS @+0x850
typedef union CORTEZ_CORE_STATUS_reg_tag {
    struct {
        uint32_t VALID_OUT : 1; // @[0:0]
        uint32_t reserved : 31; // @[31:1]
    } fields;
    uint32_t value;
} CORTEZ_CORE_STATUS_reg_t;
