// Generated by  grogu  starting from JINJA templated  reg_defines.h  file

#pragma once

// Array registers are defined only once

// hl_neuron_regfile_WEIGHT_0 @+0x0
typedef union hl_neuron_regfile_WEIGHT_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_0_reg_t;

// hl_neuron_regfile_WEIGHT_1 @+0x1
typedef union hl_neuron_regfile_WEIGHT_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_1_reg_t;

// hl_neuron_regfile_WEIGHT_2 @+0x2
typedef union hl_neuron_regfile_WEIGHT_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_2_reg_t;

// hl_neuron_regfile_WEIGHT_3 @+0x3
typedef union hl_neuron_regfile_WEIGHT_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_3_reg_t;

// hl_neuron_regfile_WEIGHT_4 @+0x4
typedef union hl_neuron_regfile_WEIGHT_4_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_4_reg_t;

// hl_neuron_regfile_WEIGHT_5 @+0x5
typedef union hl_neuron_regfile_WEIGHT_5_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_5_reg_t;

// hl_neuron_regfile_WEIGHT_6 @+0x6
typedef union hl_neuron_regfile_WEIGHT_6_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_6_reg_t;

// hl_neuron_regfile_WEIGHT_7 @+0x7
typedef union hl_neuron_regfile_WEIGHT_7_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_7_reg_t;

// hl_neuron_regfile_WEIGHT_8 @+0x8
typedef union hl_neuron_regfile_WEIGHT_8_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_8_reg_t;

// hl_neuron_regfile_WEIGHT_9 @+0x9
typedef union hl_neuron_regfile_WEIGHT_9_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_9_reg_t;

// hl_neuron_regfile_WEIGHT_10 @+0xa
typedef union hl_neuron_regfile_WEIGHT_10_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_10_reg_t;

// hl_neuron_regfile_WEIGHT_11 @+0xb
typedef union hl_neuron_regfile_WEIGHT_11_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_11_reg_t;

// hl_neuron_regfile_WEIGHT_12 @+0xc
typedef union hl_neuron_regfile_WEIGHT_12_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_12_reg_t;

// hl_neuron_regfile_WEIGHT_13 @+0xd
typedef union hl_neuron_regfile_WEIGHT_13_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_13_reg_t;

// hl_neuron_regfile_WEIGHT_14 @+0xe
typedef union hl_neuron_regfile_WEIGHT_14_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_14_reg_t;

// hl_neuron_regfile_WEIGHT_15 @+0xf
typedef union hl_neuron_regfile_WEIGHT_15_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_15_reg_t;

// hl_neuron_regfile_WEIGHT_16 @+0x10
typedef union hl_neuron_regfile_WEIGHT_16_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_16_reg_t;

// hl_neuron_regfile_WEIGHT_17 @+0x11
typedef union hl_neuron_regfile_WEIGHT_17_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_17_reg_t;

// hl_neuron_regfile_WEIGHT_18 @+0x12
typedef union hl_neuron_regfile_WEIGHT_18_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_18_reg_t;

// hl_neuron_regfile_WEIGHT_19 @+0x13
typedef union hl_neuron_regfile_WEIGHT_19_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_19_reg_t;

// hl_neuron_regfile_WEIGHT_20 @+0x14
typedef union hl_neuron_regfile_WEIGHT_20_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_20_reg_t;

// hl_neuron_regfile_WEIGHT_21 @+0x15
typedef union hl_neuron_regfile_WEIGHT_21_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_21_reg_t;

// hl_neuron_regfile_WEIGHT_22 @+0x16
typedef union hl_neuron_regfile_WEIGHT_22_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_22_reg_t;

// hl_neuron_regfile_WEIGHT_23 @+0x17
typedef union hl_neuron_regfile_WEIGHT_23_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_23_reg_t;

// hl_neuron_regfile_WEIGHT_24 @+0x18
typedef union hl_neuron_regfile_WEIGHT_24_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_24_reg_t;

// hl_neuron_regfile_WEIGHT_25 @+0x19
typedef union hl_neuron_regfile_WEIGHT_25_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_25_reg_t;

// hl_neuron_regfile_WEIGHT_26 @+0x1a
typedef union hl_neuron_regfile_WEIGHT_26_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_26_reg_t;

// hl_neuron_regfile_WEIGHT_27 @+0x1b
typedef union hl_neuron_regfile_WEIGHT_27_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_27_reg_t;

// hl_neuron_regfile_WEIGHT_28 @+0x1c
typedef union hl_neuron_regfile_WEIGHT_28_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_28_reg_t;

// hl_neuron_regfile_WEIGHT_29 @+0x1d
typedef union hl_neuron_regfile_WEIGHT_29_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_29_reg_t;

// hl_neuron_regfile_WEIGHT_30 @+0x1e
typedef union hl_neuron_regfile_WEIGHT_30_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_30_reg_t;

// hl_neuron_regfile_WEIGHT_31 @+0x1f
typedef union hl_neuron_regfile_WEIGHT_31_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_31_reg_t;

// hl_neuron_regfile_WEIGHT_32 @+0x20
typedef union hl_neuron_regfile_WEIGHT_32_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_32_reg_t;

// hl_neuron_regfile_WEIGHT_33 @+0x21
typedef union hl_neuron_regfile_WEIGHT_33_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_33_reg_t;

// hl_neuron_regfile_WEIGHT_34 @+0x22
typedef union hl_neuron_regfile_WEIGHT_34_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_34_reg_t;

// hl_neuron_regfile_WEIGHT_35 @+0x23
typedef union hl_neuron_regfile_WEIGHT_35_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_35_reg_t;

// hl_neuron_regfile_BIAS @+0x24
typedef union hl_neuron_regfile_BIAS_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_BIAS_reg_t;
