// Generated by  grogu  starting from JINJA templated  reg_defines.h  file

#pragma once

// Array registers are defined only once

// hl_neuron_regfile_WEIGHT_0 @+0x0
typedef union hl_neuron_regfile_WEIGHT_0_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_0_reg_t;

// hl_neuron_regfile_WEIGHT_1 @+0x1
typedef union hl_neuron_regfile_WEIGHT_1_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_1_reg_t;

// hl_neuron_regfile_WEIGHT_2 @+0x2
typedef union hl_neuron_regfile_WEIGHT_2_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_2_reg_t;

// hl_neuron_regfile_WEIGHT_3 @+0x3
typedef union hl_neuron_regfile_WEIGHT_3_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_3_reg_t;

// hl_neuron_regfile_WEIGHT_4 @+0x4
typedef union hl_neuron_regfile_WEIGHT_4_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_4_reg_t;

// hl_neuron_regfile_WEIGHT_5 @+0x5
typedef union hl_neuron_regfile_WEIGHT_5_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_5_reg_t;

// hl_neuron_regfile_WEIGHT_6 @+0x6
typedef union hl_neuron_regfile_WEIGHT_6_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_6_reg_t;

// hl_neuron_regfile_WEIGHT_7 @+0x7
typedef union hl_neuron_regfile_WEIGHT_7_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_7_reg_t;

// hl_neuron_regfile_WEIGHT_8 @+0x8
typedef union hl_neuron_regfile_WEIGHT_8_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_8_reg_t;

// hl_neuron_regfile_WEIGHT_9 @+0x9
typedef union hl_neuron_regfile_WEIGHT_9_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_9_reg_t;

// hl_neuron_regfile_WEIGHT_10 @+0xa
typedef union hl_neuron_regfile_WEIGHT_10_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_10_reg_t;

// hl_neuron_regfile_WEIGHT_11 @+0xb
typedef union hl_neuron_regfile_WEIGHT_11_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_11_reg_t;

// hl_neuron_regfile_WEIGHT_12 @+0xc
typedef union hl_neuron_regfile_WEIGHT_12_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_12_reg_t;

// hl_neuron_regfile_WEIGHT_13 @+0xd
typedef union hl_neuron_regfile_WEIGHT_13_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_13_reg_t;

// hl_neuron_regfile_WEIGHT_14 @+0xe
typedef union hl_neuron_regfile_WEIGHT_14_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_14_reg_t;

// hl_neuron_regfile_WEIGHT_15 @+0xf
typedef union hl_neuron_regfile_WEIGHT_15_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_WEIGHT_15_reg_t;

// hl_neuron_regfile_BIAS @+0x10
typedef union hl_neuron_regfile_BIAS_reg_tag {
    struct {
        uint32_t data : 8; // @[7:0]
    } fields;
    uint32_t value;
} hl_neuron_regfile_BIAS_reg_t;
